# Generated by Django 5.2.8 on 2025-12-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя и Фамилия')),
                ('photo', models.ImageField(upload_to='members/', verbose_name='Фото')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Краткое описание/Биография')),
            ],
            options={
                'verbose_name': 'Член ассоциации',
                'verbose_name_plural': 'Члены ассоциации',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнера')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
