# Generated by Django 5.2.9 on 2025-12-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationmember',
            options={'verbose_name': 'Association Member', 'verbose_name_plural': 'Association Members'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='description',
            field=models.TextField(verbose_name='Short Bio/Description'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='photo',
            field=models.ImageField(upload_to='members/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Website Link'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Partner Name'),
        ),
    ]
