# Generated by Django 5.2.9 on 2025-12-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_associationmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contract',
            field=models.ImageField(blank=True, null=True, upload_to='partners/contracts/', verbose_name='Contract Document/Photo'),
        ),
    ]
