# Generated by Django 5.2.9 on 2025-12-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('photo', models.ImageField(upload_to='members/', verbose_name='Photo')),
                ('position', models.CharField(default='President', max_length=255, verbose_name='Position')),
                ('description', models.TextField(verbose_name='Bio/Message')),
            ],
            options={
                'verbose_name': 'President',
                'verbose_name_plural': 'Presidents',
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, help_text='Max 300 chars for better display', verbose_name='Description'),
        ),
    ]
