# Generated by Django 5.2.9 on 2026-01-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_president_alter_partner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationmember',
            name='photo',
            field=models.ImageField(upload_to='media/members/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contract',
            field=models.ImageField(blank=True, null=True, upload_to='media/partners/contracts/', verbose_name='Contract Document/Photo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='media/partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='president',
            name='photo',
            field=models.ImageField(upload_to='media/members/', verbose_name='Photo'),
        ),
    ]
