# Generated by Django 5.2.9 on 2026-01-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_associationmember_photo_alter_partner_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('sponsor', 'Sponsor'), ('media', 'Media Partner'), ('tech', 'Technology Partner'), ('venue', 'Venue Partner'), ('other', 'Other')], default='other', max_length=20, verbose_name='Partner Category'),
        ),
    ]
