# Generated by Django 5.2.9 on 2026-01-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('github', 'GitHub'), ('reddit', 'Reddit'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('twitch', 'Twitch'), ('vk', 'VK (VKontakte)'), ('wechat', 'WeChat'), ('line', 'Line'), ('viber', 'Viber'), ('other', 'Other')], max_length=50, unique=True, verbose_name='Social Network')),
                ('url', models.URLField(verbose_name='Profile URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
                'ordering': ['order', 'name'],
            },
        ),
    ]
