# Generated by Django 5.2.9 on 2026-02-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_socialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('duration', models.CharField(blank=True, help_text='Например: 1-2 недели, с пятницы по воскресенье', max_length=200, verbose_name='Длительность')),
                ('location', models.CharField(blank=True, help_text='Например: тёплые страны, берег моря', max_length=300, verbose_name='Место проведения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/products/', verbose_name='Изображение продукта')),
                ('icon', models.CharField(default='fas fa-star', help_text='Например: fas fa-child, fas fa-water, fas fa-ship', max_length=100, verbose_name='Font Awesome иконка')),
                ('features', models.TextField(blank=True, help_text='Каждая особенность с новой строки', verbose_name='Дополнительные особенности')),
                ('price_info', models.CharField(blank=True, max_length=300, verbose_name='Информация о цене')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, help_text='Меньшее число = выше на странице', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Основной продукт IESA',
                'verbose_name_plural': 'Основные продукты IESA',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название преимущества')),
                ('category', models.CharField(choices=[('medical', 'Медицинское обслуживание'), ('shopping', 'Покупки и магазины'), ('services', 'Услуги членов ассоциации'), ('events', 'Спортивные мероприятия'), ('advertising', 'Реклама и продвижение'), ('education', 'Обучение и курсы'), ('travel', 'Путешествия и туризм'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание преимущества')),
                ('discount_info', models.CharField(blank=True, help_text='Например: 20%, 15% на первый уровень', max_length=200, verbose_name='Информация о скидке')),
                ('icon', models.CharField(default='fas fa-gift', max_length=100, verbose_name='Font Awesome иконка')),
                ('color', models.CharField(default='primary', help_text='primary, success, info, warning, danger или hex код', max_length=50, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('partner_info', models.CharField(blank=True, max_length=300, verbose_name='Партнёр/поставщик услуги')),
                ('terms', models.TextField(blank=True, help_text='Как член ассоциации может получить эту скидку', verbose_name='Условия получения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Преимущество члена ассоциации',
                'verbose_name_plural': 'Преимущества членов ассоциации',
                'ordering': ['order', 'category', '-created_at'],
            },
        ),
    ]
