# Generated by Django 5.2.9 on 2026-02-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coreproduct_memberbenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение продукта'),
        ),
    ]
