# Generated by Django 5.2.9 on 2026-02-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_coreproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationmember',
            name='photo',
            field=models.ImageField(upload_to='members/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contract',
            field=models.ImageField(blank=True, null=True, upload_to='partners/contracts/', verbose_name='Contract Document/Photo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='president',
            name='photo',
            field=models.ImageField(upload_to='members/', verbose_name='Photo'),
        ),
    ]
