# Generated by Django 5.2.9 on 2026-02-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_associationmember_photo_alter_partner_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmember',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Short Bio/Description (German)'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='description_fr',
            field=models.TextField(blank=True, verbose_name='Short Bio/Description (French)'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Short Bio/Description (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='position_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position (German)'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='position_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position (French)'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='position_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Описание продукта (German)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='description_fr',
            field=models.TextField(blank=True, verbose_name='Описание продукта (French)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Описание продукта (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='duration_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Длительность (German)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='duration_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Длительность (French)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='duration_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Длительность (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='features_de',
            field=models.TextField(blank=True, verbose_name='Дополнительные особенности (German)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='features_fr',
            field=models.TextField(blank=True, verbose_name='Дополнительные особенности (French)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='features_uk',
            field=models.TextField(blank=True, verbose_name='Дополнительные особенности (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='location_de',
            field=models.CharField(blank=True, max_length=300, verbose_name='Место проведения (German)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='location_fr',
            field=models.CharField(blank=True, max_length=300, verbose_name='Место проведения (French)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='location_uk',
            field=models.CharField(blank=True, max_length=300, verbose_name='Место проведения (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='price_info_de',
            field=models.CharField(blank=True, max_length=300, verbose_name='Информация о цене (German)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='price_info_fr',
            field=models.CharField(blank=True, max_length=300, verbose_name='Информация о цене (French)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='price_info_uk',
            field=models.CharField(blank=True, max_length=300, verbose_name='Информация о цене (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название продукта (German)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название продукта (French)'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название продукта (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Description (German)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_fr',
            field=models.TextField(blank=True, verbose_name='Description (French)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Description (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='president',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Bio/Message (German)'),
        ),
        migrations.AddField(
            model_name='president',
            name='description_fr',
            field=models.TextField(blank=True, verbose_name='Bio/Message (French)'),
        ),
        migrations.AddField(
            model_name='president',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Bio/Message (Ukrainian)'),
        ),
        migrations.AddField(
            model_name='president',
            name='position_de',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position (German)'),
        ),
        migrations.AddField(
            model_name='president',
            name='position_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position (French)'),
        ),
        migrations.AddField(
            model_name='president',
            name='position_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position (Ukrainian)'),
        ),
    ]
