# Generated by Django 5.2.9 on 2026-02-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_associationmember_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmember',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Short Bio/Description'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание продукта'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='duration_en',
            field=models.CharField(blank=True, help_text='Например: 1-2 недели, с пятницы по воскресенье', max_length=200, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='features_en',
            field=models.TextField(blank=True, help_text='Каждая особенность с новой строки', null=True, verbose_name='Дополнительные особенности'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='location_en',
            field=models.CharField(blank=True, help_text='Например: тёплые страны, берег моря', max_length=300, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='price_info_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Информация о цене'),
        ),
        migrations.AddField(
            model_name='coreproduct',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Описание преимущества'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание преимущества'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Описание преимущества'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание преимущества'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='discount_info_de',
            field=models.CharField(blank=True, help_text='Например: 20%, 15% на первый уровень', max_length=200, null=True, verbose_name='Информация о скидке'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='discount_info_en',
            field=models.CharField(blank=True, help_text='Например: 20%, 15% на первый уровень', max_length=200, null=True, verbose_name='Информация о скидке'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='discount_info_fr',
            field=models.CharField(blank=True, help_text='Например: 20%, 15% на первый уровень', max_length=200, null=True, verbose_name='Информация о скидке'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='discount_info_uk',
            field=models.CharField(blank=True, help_text='Например: 20%, 15% на первый уровень', max_length=200, null=True, verbose_name='Информация о скидке'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, help_text='Max 300 chars for better display', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='president',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Bio/Message'),
        ),
        migrations.AddField(
            model_name='president',
            name='position_en',
            field=models.CharField(default='President', max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Short Bio/Description'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Short Bio/Description'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Short Bio/Description'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='position_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='position_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='position_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='duration_de',
            field=models.CharField(blank=True, help_text='Например: 1-2 недели, с пятницы по воскресенье', max_length=200, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='duration_fr',
            field=models.CharField(blank=True, help_text='Например: 1-2 недели, с пятницы по воскресенье', max_length=200, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='duration_uk',
            field=models.CharField(blank=True, help_text='Например: 1-2 недели, с пятницы по воскресенье', max_length=200, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='features_de',
            field=models.TextField(blank=True, help_text='Каждая особенность с новой строки', null=True, verbose_name='Дополнительные особенности'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='features_fr',
            field=models.TextField(blank=True, help_text='Каждая особенность с новой строки', null=True, verbose_name='Дополнительные особенности'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='features_uk',
            field=models.TextField(blank=True, help_text='Каждая особенность с новой строки', null=True, verbose_name='Дополнительные особенности'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='location_de',
            field=models.CharField(blank=True, help_text='Например: тёплые страны, берег моря', max_length=300, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='location_fr',
            field=models.CharField(blank=True, help_text='Например: тёплые страны, берег моря', max_length=300, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='location_uk',
            field=models.CharField(blank=True, help_text='Например: тёплые страны, берег моря', max_length=300, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='price_info_de',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Информация о цене'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='price_info_fr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Информация о цене'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='price_info_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Информация о цене'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_de',
            field=models.TextField(blank=True, help_text='Max 300 chars for better display', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Max 300 chars for better display', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description_uk',
            field=models.TextField(blank=True, help_text='Max 300 chars for better display', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='president',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Bio/Message'),
        ),
        migrations.AlterField(
            model_name='president',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Bio/Message'),
        ),
        migrations.AlterField(
            model_name='president',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Bio/Message'),
        ),
        migrations.AlterField(
            model_name='president',
            name='position_de',
            field=models.CharField(default='President', max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='president',
            name='position_fr',
            field=models.CharField(default='President', max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='president',
            name='position_uk',
            field=models.CharField(default='President', max_length=255, null=True, verbose_name='Position'),
        ),
    ]
