# Generated by Django 5.2.9 on 2026-02-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_associationmember_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbenefit',
            name='partner_info_de',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Партнёр/поставщик услуги'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='partner_info_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Партнёр/поставщик услуги'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='partner_info_fr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Партнёр/поставщик услуги'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='partner_info_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Партнёр/поставщик услуги'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='terms_de',
            field=models.TextField(blank=True, help_text='Как член ассоциации может получить эту скидку', null=True, verbose_name='Условия получения'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='terms_en',
            field=models.TextField(blank=True, help_text='Как член ассоциации может получить эту скидку', null=True, verbose_name='Условия получения'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='terms_fr',
            field=models.TextField(blank=True, help_text='Как член ассоциации может получить эту скидку', null=True, verbose_name='Условия получения'),
        ),
        migrations.AddField(
            model_name='memberbenefit',
            name='terms_uk',
            field=models.TextField(blank=True, help_text='Как член ассоциации может получить эту скидку', null=True, verbose_name='Условия получения'),
        ),
    ]
