# Generated by Django 5.2.9 on 2026-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_real_benefits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreproduct',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Core IESA product', 'verbose_name_plural': 'Core IESA products'},
        ),
        migrations.AlterModelOptions(
            name='memberbenefit',
            options={'ordering': ['order', 'category', '-created_at'], 'verbose_name': 'Member benefit', 'verbose_name_plural': 'Member benefits'},
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='description',
            field=models.TextField(verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='duration',
            field=models.CharField(blank=True, help_text='E.g.: 1-2 weeks, Friday to Sunday', max_length=200, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='duration_de',
            field=models.CharField(blank=True, help_text='E.g.: 1-2 weeks, Friday to Sunday', max_length=200, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='duration_en',
            field=models.CharField(blank=True, help_text='E.g.: 1-2 weeks, Friday to Sunday', max_length=200, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='duration_fr',
            field=models.CharField(blank=True, help_text='E.g.: 1-2 weeks, Friday to Sunday', max_length=200, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='duration_uk',
            field=models.CharField(blank=True, help_text='E.g.: 1-2 weeks, Friday to Sunday', max_length=200, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='features',
            field=models.TextField(blank=True, help_text='One feature per line', verbose_name='Additional features'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='features_de',
            field=models.TextField(blank=True, help_text='One feature per line', null=True, verbose_name='Additional features'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='features_en',
            field=models.TextField(blank=True, help_text='One feature per line', null=True, verbose_name='Additional features'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='features_fr',
            field=models.TextField(blank=True, help_text='One feature per line', null=True, verbose_name='Additional features'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='features_uk',
            field=models.TextField(blank=True, help_text='One feature per line', null=True, verbose_name='Additional features'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='icon',
            field=models.CharField(default='fas fa-star', help_text='E.g.: fas fa-child, fas fa-water, fas fa-ship', max_length=100, verbose_name='Font Awesome icon'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='location',
            field=models.CharField(blank=True, help_text='E.g.: warm countries, seaside', max_length=300, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='location_de',
            field=models.CharField(blank=True, help_text='E.g.: warm countries, seaside', max_length=300, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='location_en',
            field=models.CharField(blank=True, help_text='E.g.: warm countries, seaside', max_length=300, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='location_fr',
            field=models.CharField(blank=True, help_text='E.g.: warm countries, seaside', max_length=300, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='location_uk',
            field=models.CharField(blank=True, help_text='E.g.: warm countries, seaside', max_length=300, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower number = higher on page', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='price_info',
            field=models.CharField(blank=True, max_length=300, verbose_name='Price info'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='price_info_de',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Price info'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='price_info_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Price info'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='price_info_fr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Price info'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='price_info_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Price info'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='coreproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical services'), ('shopping', 'Shopping & retail'), ('services', 'Member services'), ('events', 'Sports events'), ('advertising', 'Advertising & promotion'), ('education', 'Education & courses'), ('travel', 'Travel & tourism'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='color',
            field=models.CharField(default='primary', help_text='primary, success, info, warning, danger or hex code', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='description',
            field=models.TextField(verbose_name='Benefit description'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Benefit description'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Benefit description'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Benefit description'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Benefit description'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='discount_info',
            field=models.CharField(blank=True, help_text='E.g.: 20%, 15% on first level', max_length=200, verbose_name='Discount info'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='discount_info_de',
            field=models.CharField(blank=True, help_text='E.g.: 20%, 15% on first level', max_length=200, null=True, verbose_name='Discount info'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='discount_info_en',
            field=models.CharField(blank=True, help_text='E.g.: 20%, 15% on first level', max_length=200, null=True, verbose_name='Discount info'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='discount_info_fr',
            field=models.CharField(blank=True, help_text='E.g.: 20%, 15% on first level', max_length=200, null=True, verbose_name='Discount info'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='discount_info_uk',
            field=models.CharField(blank=True, help_text='E.g.: 20%, 15% on first level', max_length=200, null=True, verbose_name='Discount info'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='icon',
            field=models.CharField(default='fas fa-gift', max_length=100, verbose_name='Font Awesome icon'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='partner_info',
            field=models.CharField(blank=True, max_length=300, verbose_name='Partner/service provider'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='partner_info_de',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Partner/service provider'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='partner_info_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Partner/service provider'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='partner_info_fr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Partner/service provider'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='partner_info_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Partner/service provider'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='terms',
            field=models.TextField(blank=True, help_text='How a member can receive this discount', verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='terms_de',
            field=models.TextField(blank=True, help_text='How a member can receive this discount', null=True, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='terms_en',
            field=models.TextField(blank=True, help_text='How a member can receive this discount', null=True, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='terms_fr',
            field=models.TextField(blank=True, help_text='How a member can receive this discount', null=True, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='terms_uk',
            field=models.TextField(blank=True, help_text='How a member can receive this discount', null=True, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Benefit name'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Benefit name'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Benefit name'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Benefit name'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Benefit name'),
        ),
        migrations.AlterField(
            model_name='memberbenefit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
