# Generated by Django 5.2.9 on 2026-03-04 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_coreproduct_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('reason', models.CharField(choices=[('partner_access', 'Partner portal access request'), ('account_issue', 'Account / membership issue'), ('verification', 'Verification request'), ('other', 'Other')], default='other', max_length=30, verbose_name='Reason')),
                ('message', models.TextField(verbose_name='Message')),
                ('requested_url', models.CharField(blank=True, max_length=500, verbose_name='Requested URL')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('declined', 'Declined')], default='new', max_length=12, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_appeals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin appeal',
                'verbose_name_plural': 'Admin appeals',
                'ordering': ['-created_at'],
            },
        ),
    ]
