# Generated by Django 5.2.9 on 2026-02-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
    ]
