# Generated by Django 5.2.9 on 2026-01-17 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Admins'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
