# Generated by Django 5.2.9 on 2026-01-18 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_admins_conversation_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Message Text'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted', '-created_at'], name='messaging_m_is_dele_8286cb_idx'),
        ),
    ]
