#!/usr/bin/env python3
"""
Bulk-translate all untranslated msgid==msgstr entries in DE and FR .po files.
Project-specific strings only (Django framework strings are skipped).
"""
import re
import os

# ============================================================
# GERMAN TRANSLATIONS
# ============================================================
DE = {
    # Events
    "Events": "Veranstaltungen",
    "events": "Veranstaltungen",
    "gatherings": "Treffen",
    "Date & time:": "Datum & Uhrzeit:",
    "Location:": "Ort:",
    "DESCRIPTION": "BESCHREIBUNG",
    "Back to events": "Zurück zu Veranstaltungen",
    "EVENTS CALENDAR": "VERANSTALTUNGSKALENDER",
    "Upcoming Events & Gatherings": "Kommende Veranstaltungen & Treffen",
    "Join us for exciting experiences and networking opportunities": "Begleiten Sie uns zu spannenden Erlebnissen und Networking-Möglichkeiten",
    "Join to RSVP, comment and engage with members": "Melden Sie sich an, um teilzunehmen, zu kommentieren und mit Mitgliedern in Kontakt zu treten",
    "All posts": "Alle Beiträge",
    "Search events...": "Veranstaltungen suchen...",
    "Search events": "Veranstaltungen suchen",
    "Upcoming": "Bevorstehend",
    "All events": "Alle Veranstaltungen",
    "Past": "Vergangen",
    "Date ↑": "Datum ↑",
    "Date ↓": "Datum ↓",
    "Title A→Z": "Titel A→Z",
    "Title Z→A": "Titel Z→A",
    "All categories": "Alle Kategorien",
    "Loading...": "Wird geladen...",
    "Back to blog": "Zurück zum Blog",

    # Post creation
    "Create a new post": "Neuen Beitrag erstellen",
    "CREATE CONTENT": "INHALT ERSTELLEN",
    "Publish New Article or Announcement": "Neuen Artikel oder Ankündigung veröffentlichen",
    "Use our advanced editor: fonts, colors, lists, quotes and preview before publishing": "Nutzen Sie unseren erweiterten Editor: Schriften, Farben, Listen, Zitate und Vorschau vor der Veröffentlichung",
    "Rich formatting: headings, lists, links, quotes, text and background colors.": "Reichhaltige Formatierung: Überschriften, Listen, Links, Zitate, Text- und Hintergrundfarben.",
    "Preview": "Vorschau",
    "Create and submit for review": "Erstellen und zur Überprüfung einreichen",
    "Submitting...": "Wird eingereicht...",
    "Live preview": "Live-Vorschau",
    "Preview image": "Vorschaubild",
    "Add an image for preview": "Bild für Vorschau hinzufügen",
    "Draft preview": "Entwurfsvorschau",
    "Post Title": "Beitragstitel",
    "Description will appear here after editing.": "Beschreibung erscheint hier nach der Bearbeitung.",
    "Please enter a post title": "Bitte geben Sie einen Beitragstitel ein",
    "Please enter post content": "Bitte geben Sie den Beitragsinhalt ein",

    # Blog / Comments
    "Anonymous": "Anonym",
    "views": "Aufrufe",
    "COMMENTS": "KOMMENTARE",
    "Leave a comment": "Kommentar hinterlassen",
    "Your comment...": "Ihr Kommentar...",
    "Send": "Senden",
    "To comment, please": "Um zu kommentieren, bitte",
    "sign in": "anmelden",
    "or": "oder",
    "register": "registrieren",
    "RECOMMENDED POSTS": "EMPFOHLENE BEITRÄGE",
    "Community & Blog": "Community & Blog",
    "COMMUNITY": "GEMEINSCHAFT",
    "Share Ideas, Events & News": "Ideen, Veranstaltungen & Neuigkeiten teilen",
    "Sign in or register to access the community": "Anmelden oder registrieren, um auf die Community zuzugreifen",
    "Join our community to create posts, comment and engage with members": "Treten Sie unserer Community bei, um Beiträge zu erstellen, zu kommentieren und mit Mitgliedern in Kontakt zu treten",
    "All Posts": "Alle Beiträge",
    "Search posts...": "Beiträge suchen...",
    "Search posts": "Beiträge suchen",
    "All statuses": "Alle Status",
    "Published": "Veröffentlicht",
    "Pending": "Ausstehend",
    "Latest": "Neueste",
    "Popular": "Beliebt",
    "Trending": "Im Trend",
    "Create Post": "Beitrag erstellen",
    "No Posts Yet": "Noch keine Beiträge",
    "Be the first to share news or ideas with the community": "Seien Sie der Erste, der Neuigkeiten oder Ideen mit der Community teilt",
    "Create First Post": "Ersten Beitrag erstellen",
    "Join Community": "Community beitreten",

    # Benefits
    "Member Benefits": "Mitgliedervorteile",
    "IESA Member Benefits": "IESA-Mitgliedervorteile",
    "Get exclusive discounts and benefits as a member of our association": "Erhalten Sie exklusive Rabatte und Vorteile als Mitglied unseres Vereins",
    "Terms of access": "Zugangsbedingungen",
    "Want access to these benefits?": "Möchten Sie Zugang zu diesen Vorteilen?",
    "Become an IESA member and receive exclusive discounts and privileges": "Werden Sie IESA-Mitglied und erhalten Sie exklusive Rabatte und Privilegien",
    "Join now": "Jetzt beitreten",
    "Back to home": "Zurück zur Startseite",
    "Benefits coming soon": "Vorteile kommen bald",
    "We are working on exclusive offers for our members": "Wir arbeiten an exklusiven Angeboten für unsere Mitglieder",

    # Partners / Teams
    "Teams": "Teams",
    "Teams · Corporate": "Teams · Unternehmen",
    "Sponsor": "Sponsor",
    "Partner": "Partner",
    "Details": "Details",

    # Gallery
    "PHOTO GALLERY": "FOTOGALERIE",
    "Moments From Our Community": "Momente aus unserer Gemeinschaft",
    "See how we work, train and create memories together": "Sehen Sie, wie wir zusammen arbeiten, trainieren und Erinnerungen schaffen",
    "Photo": "Foto",
    "View photo": "Foto ansehen",
    "Previous": "Zurück",
    "Next": "Weiter",
    "No photos yet": "Noch keine Fotos",
    "Add photos from events or projects to inspire members.": "Fügen Sie Fotos von Veranstaltungen oder Projekten hinzu, um Mitglieder zu inspirieren.",
    "Go to community": "Zur Community",

    # Messaging
    "Chat with %(first)s %(last)s": "Chat mit %(first)s %(last)s",
    "Profile": "Profil",
    "Search": "Suche",
    "%(name)s is typing": "%(name)s tippt",
    "Type a message...": "Nachricht eingeben...",
    "Attach file": "Datei anhängen",
    "Search messages": "Nachrichten suchen",
    "Search...": "Suchen...",
    "Edit": "Bearbeiten",
    "Delete": "Löschen",
    "Today": "Heute",
    "Yesterday": "Gestern",
    "(edited)": "(bearbeitet)",
    "Edit message:": "Nachricht bearbeiten:",
    "Delete message?": "Nachricht löschen?",
    "No results found": "Keine Ergebnisse gefunden",
    "Messages": "Nachrichten",
    "New chat": "Neuer Chat",
    "Search chats...": "Chats suchen...",
    "No chats": "Keine Chats",
    "Select a chat": "Chat auswählen",
    "Or start a new conversation": "Oder eine neue Unterhaltung beginnen",
    "Search users...": "Benutzer suchen...",
    "Type a name to search": "Namen eingeben, um zu suchen",
    "No messages": "Keine Nachrichten",
    "No users found": "Keine Benutzer gefunden",

    # Notifications
    "Notifications": "Benachrichtigungen",
    "Stay updated with your activity": "Bleiben Sie auf dem Laufenden",
    "Mark all as read": "Alle als gelesen markieren",
    "Unread": "Ungelesen",
    "All notifications marked as read": "Alle Benachrichtigungen als gelesen markiert",
    "New": "Neu",
    "ago": "her",
    "View": "Ansehen",
    "Delete notification": "Benachrichtigung löschen",
    "Notifications pagination": "Benachrichtigungen Seitennavigation",
    "No notifications yet": "Noch keine Benachrichtigungen",
    "You'll see notifications here when someone interacts with your content.": "Hier sehen Sie Benachrichtigungen, wenn jemand mit Ihren Inhalten interagiert.",
    "Explore Posts": "Beiträge entdecken",

    # Error pages
    "404 - Page not found": "404 – Seite nicht gefunden",
    "Page not found": "Seite nicht gefunden",
    "Maybe you were looking for:": "Vielleicht suchen Sie nach:",
    "Search the site...": "Website durchsuchen...",
    "500 - Internal server error": "500 – Interner Serverfehler",
    "Internal server error": "Interner Serverfehler",
    "Go back": "Zurück",
    "If the problem persists, please contact our support team.": "Wenn das Problem bestehen bleibt, wenden Sie sich bitte an unser Support-Team.",

    # Base / Navigation
    "IESA ROOT": "IESA ROOT",
    "Skip to main content": "Zum Hauptinhalt springen",
    "Attention!": "Achtung!",
    "Site is under active development. Some features may not work correctly.": "Die Website befindet sich in aktiver Entwicklung. Einige Funktionen funktionieren möglicherweise nicht korrekt.",
    "Main navigation": "Hauptnavigation",
    "IESA Home": "IESA Startseite",
    "IESA Logo": "IESA Logo",
    "Toggle navigation": "Navigation umschalten",
    "IESA Association. All rights reserved.": "IESA Verein. Alle Rechte vorbehalten.",
    "LINKS": "LINKS",
    "CONTACTS": "KONTAKTE",
    "SOCIAL": "SOZIALE NETZWERKE",

    # Model fields
    "Permanent ID": "Permanente ID",
    "Card active": "Karte aktiv",
    "Card issued at": "Karte ausgestellt am",
    "Membership Status": "Mitgliedschaftsstatus",
    "TOTP Secret": "TOTP-Geheimnis",
    "Pseudonym": "Pseudonym",
    "User Account": "Benutzerkonto",
    "Company Name": "Firmenname",
    "Business Type": "Geschäftsart",
    "Created At": "Erstellt am",
    "Member": "Mitglied",
    "Service Type": "Dienstleistungsart",
    "Service Description": "Dienstleistungsbeschreibung",
    "Cost": "Kosten",
    "Comments": "Kommentare",
    "PIN Verified": "PIN bestätigt",
    "Visit Time": "Besuchszeit",
    "Visits": "Besuche",

    # Login
    "Welcome back": "Willkommen zurück",
    "Sign in to manage your profile, create posts and discover events.": "Melden Sie sich an, um Ihr Profil zu verwalten, Beiträge zu erstellen und Veranstaltungen zu entdecken.",
    "Quick Access": "Schnellzugriff",
    "Community Engagement": "Community-Engagement",
    "Event Updates": "Veranstaltungsupdates",
    "SIGN IN": "ANMELDEN",
    "Access your profile and connect with the community.": "Greifen Sie auf Ihr Profil zu und verbinden Sie sich mit der Community.",
    "Sign in failed!": "Anmeldung fehlgeschlagen!",
    "Invalid username or password. Please try again.": "Ungültiger Benutzername oder Passwort. Bitte versuchen Sie es erneut.",
    "Don't have an account?": "Noch kein Konto?",
    "Register here": "Hier registrieren",

    # Profile
    "Profile of %(username)s": "Profil von %(username)s",
    "Edit Profile": "Profil bearbeiten",
    "Your QR Code": "Ihr QR-Code",
    "Open profile by card": "Profil per Karte öffnen",
    "QR Code": "QR-Code",
    "Scan to view profile": "Scannen, um Profil anzuzeigen",
    "Download QR": "QR herunterladen",
    "Follow": "Folgen",
    "Sign in": "Anmelden",
    "to follow users": "um Benutzern zu folgen",
    "Full name": "Vollständiger Name",
    "Date of birth": "Geburtsdatum",
    "years": "Jahre",
    "Phone": "Telefon",
    "Hidden": "Versteckt",
    "Not specified": "Nicht angegeben",
    "Joined": "Beigetreten",
    "Activity Level": "Aktivitätsstufe",
    "Legend": "Legende",
    "Expert": "Experte",
    "Advanced": "Fortgeschritten",
    "Intermediate": "Mittelstufe",
    "Beginner": "Anfänger",
    "Learn about activity levels": "Mehr über Aktivitätsstufen erfahren",
    "Activity Points": "Aktivitätspunkte",
    "Progress to %(level)s:": "Fortschritt zu %(level)s:",
    "Maximum level achieved!": "Maximale Stufe erreicht!",
    "Find me": "Finden Sie mich",
    "Total posts": "Beiträge gesamt",
    "Likes received": "Erhaltene Likes",
    "Comments made": "Abgegebene Kommentare",
    "Your Posts": "Ihre Beiträge",
    "Title": "Titel",
    "Status": "Status",
    "Created": "Erstellt",
    "Actions": "Aktionen",
    "Rejected": "Abgelehnt",
    "You have no posts yet.": "Sie haben noch keine Beiträge.",
    "Create your first post": "Erstellen Sie Ihren ersten Beitrag",

    # Edit profile
    "Edit profile": "Profil bearbeiten",
    "Refresh your info, avatar and social links.": "Aktualisieren Sie Ihre Daten, Ihr Avatar und soziale Links.",
    "Basic info": "Grundinformationen",
    "First name": "Vorname",
    "Last name": "Nachname",
    "Email": "E-Mail",
    "Format: DD.MM.YYYY": "Format: TT.MM.JJJJ",
    "Phone Number": "Telefonnummer",
    "Example: +41 XX XXX XX XX": "Beispiel: +41 XX XXX XX XX",
    "Hide phone number (only admins can see it)": "Telefonnummer verbergen (nur Admins können sie sehen)",
    "Avatar": "Avatar",
    "Upload square image for best fit.": "Quadratisches Bild für beste Passform hochladen.",
    "Social & links": "Soziale Netzwerke & Links",
    "examples below": "Beispiele unten",
    "Other links": "Weitere Links",
    "one per line": "einer pro Zeile",
    "Save changes": "Änderungen speichern",
    "Cancel": "Abbrechen",

    # Public profile
    "Member since": "Mitglied seit",
    "Copy ID": "ID kopieren",
    "Verified": "Verifiziert",
    "Card Active": "Karte aktiv",
    "Activity Statistics": "Aktivitätsstatistik",
    "Posts": "Beiträge",
    "Likes": "Likes",
    "Admin Panel": "Admin-Bereich",
    "Links": "Links",
    "Website": "Webseite",
    "Other:": "Andere:",
    "Published Posts": "Veröffentlichte Beiträge",
    "No published posts yet.": "Noch keine veröffentlichten Beiträge.",
    "About": "Über",

    # Registration
    "Join IESA Today": "Treten Sie IESA heute bei",
    "Connect with Athletes": "Verbinden Sie sich mit Sportlern",
    "Share Your Journey": "Teilen Sie Ihre Reise",
    "Discover Events": "Veranstaltungen entdecken",
    "Build Your Profile": "Profil aufbauen",
    "REGISTER": "REGISTRIEREN",
    "Join the IESA community and start sharing!": "Treten Sie der IESA-Community bei und teilen Sie mit!",
    "Registration failed:": "Registrierung fehlgeschlagen:",
    "Create Account": "Konto erstellen",
    "Already have an account?": "Haben Sie bereits ein Konto?",
    "Sign in here": "Hier anmelden",

    # Member directory
    "User search": "Benutzersuche",
    "MEMBER DIRECTORY": "MITGLIEDERVERZEICHNIS",
    "Find & Connect With Members": "Mitglieder finden & verbinden",
    "Search our community by name, username, email or ID": "Durchsuchen Sie unsere Community nach Name, Benutzername, E-Mail oder ID",
    "Search by name, username, email or ID...": "Nach Name, Benutzername, E-Mail oder ID suchen...",
    "Results for": "Ergebnisse für",
    "No users found.": "Keine Benutzer gefunden.",

    # Validation
    "Password must contain at least one uppercase letter (A-Z).": "Das Passwort muss mindestens einen Großbuchstaben (A-Z) enthalten.",
    "Your password must contain at least one uppercase letter (A-Z).": "Ihr Passwort muss mindestens einen Großbuchstaben (A-Z) enthalten.",
    "Некорректный номер телефона. Допустимы цифры, пробелы, '+', '-', '()'.": "Ungültige Telefonnummer. Erlaubt sind Ziffern, Leerzeichen, '+', '-', '()'.",
    "Введите корректное имя Discord (например: username или username#1234)": "Geben Sie einen gültigen Discord-Namen ein (z.B.: username oder username#1234)",

    # Django framework strings
    "Site Maps": "Sitemaps",
    "Static Files": "Statische Dateien",
    "Syndication": "Syndikation",
    "…": "…",
    "That page number is not an integer": "Diese Seitenzahl ist keine ganze Zahl",
    "That page number is less than 1": "Diese Seitenzahl ist kleiner als 1",
    "That page contains no results": "Diese Seite enthält keine Ergebnisse",
    "Enter a valid value.": "Geben Sie einen gültigen Wert ein.",
    "Enter a valid domain name.": "Geben Sie einen gültigen Domainnamen ein.",
    "Enter a valid URL.": "Geben Sie eine gültige URL ein.",
    "Enter a valid integer.": "Geben Sie eine gültige Ganzzahl ein.",
    "Enter a valid email address.": "Geben Sie eine gültige E-Mail-Adresse ein.",
    "Enter a valid %(protocol)s address.": "Geben Sie eine gültige %(protocol)s-Adresse ein.",
    "IPv4": "IPv4",
    "IPv6": "IPv6",
    "IPv4 or IPv6": "IPv4 oder IPv6",
    "Enter only digits separated by commas.": "Geben Sie nur durch Kommas getrennte Ziffern ein.",
    "Ensure this value is %(limit_value)s (it is %(show_value)s).": "Stellen Sie sicher, dass dieser Wert %(limit_value)s ist (er ist %(show_value)s).",
    "Ensure this value is less than or equal to %(limit_value)s.": "Stellen Sie sicher, dass dieser Wert kleiner oder gleich %(limit_value)s ist.",
    "Ensure this value is greater than or equal to %(limit_value)s.": "Stellen Sie sicher, dass dieser Wert größer oder gleich %(limit_value)s ist.",
    "Ensure this value is a multiple of step size %(limit_value)s.": "Stellen Sie sicher, dass dieser Wert ein Vielfaches der Schrittgröße %(limit_value)s ist.",
    "Enter a number.": "Geben Sie eine Zahl ein.",
    "Null characters are not allowed.": "Null-Zeichen sind nicht erlaubt.",
    "and": "und",
    "%(model_name)s with this %(field_labels)s already exists.": "%(model_name)s mit diesem %(field_labels)s existiert bereits.",
    'Constraint "%(name)s" is violated.': 'Einschränkung "%(name)s" wird verletzt.',
    "Value %(value)r is not a valid choice.": "Wert %(value)r ist keine gültige Auswahl.",
    "This field cannot be null.": "Dieses Feld darf nicht null sein.",
    "This field cannot be blank.": "Dieses Feld darf nicht leer sein.",
    "%(model_name)s with this %(field_label)s already exists.": "%(model_name)s mit diesem %(field_label)s existiert bereits.",
    "Field of type: %(field_type)s": "Feld vom Typ: %(field_type)s",
    '"%(value)s" value must be either True or False.': '"%(value)s" muss entweder True oder False sein.',
    '"%(value)s" value must be either True, False, or None.': '"%(value)s" muss entweder True, False oder None sein.',
    "Boolean (Either True or False)": "Boolescher Wert (True oder False)",
    "String (up to %(max_length)s)": "Zeichenkette (bis zu %(max_length)s)",
    "String (unlimited)": "Zeichenkette (unbegrenzt)",
    "Comma-separated integers": "Durch Kommas getrennte Ganzzahlen",
    "Date (without time)": "Datum (ohne Uhrzeit)",
    "Date (with time)": "Datum (mit Uhrzeit)",
    '"%(value)s" value must be a decimal number.': '"%(value)s" muss eine Dezimalzahl sein.',
    "Decimal number": "Dezimalzahl",
    "Duration": "Dauer",
    "Email address": "E-Mail-Adresse",
    "File path": "Dateipfad",
    '"%(value)s" value must be a float.': '"%(value)s" muss eine Gleitkommazahl sein.',
    "Floating point number": "Gleitkommazahl",
    '"%(value)s" value must be an integer.': '"%(value)s" muss eine Ganzzahl sein.',
    "Integer": "Ganzzahl",
    "Big (8 byte) integer": "Große (8 Byte) Ganzzahl",
    "Small integer": "Kleine Ganzzahl",
    "IPv4 address": "IPv4-Adresse",
    "IP address": "IP-Adresse",
    '"%(value)s" value must be either None, True or False.': '"%(value)s" muss entweder None, True oder False sein.',
    "Boolean (Either True, False or None)": "Boolescher Wert (True, False oder None)",
    "Positive big integer": "Positive große Ganzzahl",
    "Positive integer": "Positive Ganzzahl",
    "Positive small integer": "Positive kleine Ganzzahl",
    "Slug (up to %(max_length)s)": "Slug (bis zu %(max_length)s)",
    "Text": "Text",
    "Time": "Zeit",
    "URL": "URL",
    "Raw binary data": "Roh-Binärdaten",
    '"%(value)s" is not a valid UUID.': '"%(value)s" ist keine gültige UUID.',
    "Universally unique identifier": "Universell eindeutiger Bezeichner",
    "File": "Datei",
    "Image": "Bild",
    "A JSON object": "Ein JSON-Objekt",
    "Value must be valid JSON.": "Wert muss gültiges JSON sein.",
    "%(model)s instance with %(field)s %(value)r is not a valid choice.": "%(model)s-Instanz mit %(field)s %(value)r ist keine gültige Auswahl.",
    "Foreign Key (type determined by related field)": "Fremdschlüssel (Typ bestimmt durch verknüpftes Feld)",
    "One-to-one relationship": "Eins-zu-eins-Beziehung",
    "%(from)s-%(to)s relationship": "%(from)s-%(to)s-Beziehung",
    "%(from)s-%(to)s relationships": "%(from)s-%(to)s-Beziehungen",
    "Many-to-many relationship": "Viele-zu-viele-Beziehung",
    ":?.!": ":?.!",
    "This field is required.": "Dieses Feld ist erforderlich.",
    "Enter a whole number.": "Geben Sie eine ganze Zahl ein.",
    "Enter a valid date.": "Geben Sie ein gültiges Datum ein.",
    "Enter a valid time.": "Geben Sie eine gültige Uhrzeit ein.",
    "Enter a valid date/time.": "Geben Sie ein gültiges Datum/eine gültige Uhrzeit ein.",
    "Enter a valid duration.": "Geben Sie eine gültige Dauer ein.",
    "The number of days must be between {min_days} and {max_days}.": "Die Anzahl der Tage muss zwischen {min_days} und {max_days} liegen.",
    "No file was submitted. Check the encoding type on the form.": "Es wurde keine Datei eingereicht. Überprüfen Sie den Kodierungstyp des Formulars.",
    "No file was submitted.": "Es wurde keine Datei eingereicht.",
    "The submitted file is empty.": "Die eingereichte Datei ist leer.",
    "Please either submit a file or check the clear checkbox, not both.": "Bitte reichen Sie entweder eine Datei ein oder markieren Sie das Kontrollkästchen zum Löschen, nicht beides.",
    "Select a valid choice. %(value)s is not one of the available choices.": "Wählen Sie eine gültige Option. %(value)s ist keine der verfügbaren Optionen.",
    "Enter a list of values.": "Geben Sie eine Liste von Werten ein.",
    "Enter a complete value.": "Geben Sie einen vollständigen Wert ein.",
    "Enter a valid UUID.": "Geben Sie eine gültige UUID ein.",
    "Enter a valid JSON.": "Geben Sie gültiges JSON ein.",
    ":": ":",
    "(Hidden field %(name)s) %(error)s": "(Verstecktes Feld %(name)s) %(error)s",
    "Order": "Reihenfolge",
    "Please correct the duplicate data for %(field)s.": "Bitte korrigieren Sie die doppelten Daten für %(field)s.",
    "Please correct the duplicate data for %(field)s, which must be unique.": "Bitte korrigieren Sie die doppelten Daten für %(field)s, die eindeutig sein müssen.",
    "Please correct the duplicate values below.": "Bitte korrigieren Sie die doppelten Werte unten.",
    "The inline value did not match the parent instance.": "Der Inline-Wert stimmte nicht mit der übergeordneten Instanz überein.",
    "Select a valid choice. That choice is not one of the available choices.": "Wählen Sie eine gültige Option. Diese Option ist nicht verfügbar.",
    '"%(pk)s" is not a valid value.': '"%(pk)s" ist kein gültiger Wert.',
    "Clear": "Löschen",
    "Currently": "Aktuell",
    "Change": "Ändern",
    "Unknown": "Unbekannt",
    "Yes": "Ja",
    "No": "Nein",
    "yes,no,maybe": "ja,nein,vielleicht",

    # File sizes
    "%s KB": "%s KB",
    "%s MB": "%s MB",
    "%s GB": "%s GB",
    "%s TB": "%s TB",
    "%s PB": "%s PB",

    # Time
    "p.m.": "nachm.",
    "a.m.": "vorm.",
    "PM": "PM",
    "AM": "AM",
    "midnight": "Mitternacht",
    "noon": "Mittag",

    # Days
    "Monday": "Montag",
    "Tuesday": "Dienstag",
    "Wednesday": "Mittwoch",
    "Thursday": "Donnerstag",
    "Friday": "Freitag",
    "Saturday": "Samstag",
    "Sunday": "Sonntag",
    "Mon": "Mo",
    "Tue": "Di",
    "Wed": "Mi",
    "Thu": "Do",
    "Fri": "Fr",
    "Sat": "Sa",
    "Sun": "So",

    # Months (full - first occurrence)
    "January": "Januar",
    "February": "Februar",
    "March": "März",
    "April": "April",
    "May": "Mai",
    "June": "Juni",
    "July": "Juli",
    "August": "August",
    "September": "September",
    "October": "Oktober",
    "November": "November",
    "December": "Dezember",

    # Months (abbreviated)
    "jan": "Jan",
    "feb": "Feb",
    "mar": "Mär",
    "apr": "Apr",
    "may": "Mai",
    "jun": "Jun",
    "jul": "Jul",
    "aug": "Aug",
    "sep": "Sep",
    "oct": "Okt",
    "nov": "Nov",
    "dec": "Dez",
    "Jan.": "Jan.",
    "Feb.": "Feb.",
    "Aug.": "Aug.",
    "Sept.": "Sept.",
    "Oct.": "Okt.",
    "Nov.": "Nov.",
    "Dec.": "Dez.",

    # More Django framework
    "This is not a valid IPv6 address.": "Dies ist keine gültige IPv6-Adresse.",
    "%(truncated_text)s…": "%(truncated_text)s…",
    ", ": ", ",
    "Forbidden": "Verboten",
    "CSRF verification failed. Request aborted.": "CSRF-Überprüfung fehlgeschlagen. Anfrage abgebrochen.",
    "More information is available with DEBUG=True.": "Weitere Informationen sind mit DEBUG=True verfügbar.",
    "No year specified": "Kein Jahr angegeben",
    "Date out of range": "Datum außerhalb des Bereichs",
    "No month specified": "Kein Monat angegeben",
    "No day specified": "Kein Tag angegeben",
    "No week specified": "Keine Woche angegeben",
    "No %(verbose_name_plural)s available": "Keine %(verbose_name_plural)s verfügbar",
    'Invalid date string "%(datestr)s" given format "%(format)s"': 'Ungültige Datumszeichenkette "%(datestr)s" für Format "%(format)s"',
    "No %(verbose_name)s found matching the query": "Kein %(verbose_name)s gefunden, das der Abfrage entspricht",
    'Page is not "last", nor can it be converted to an int.': 'Seite ist nicht "last" und kann nicht in eine Ganzzahl umgewandelt werden.',
    "Invalid page (%(page_number)s): %(message)s": "Ungültige Seite (%(page_number)s): %(message)s",
    'Empty list and "%(class_name)s.allow_empty" is False.': 'Leere Liste und "%(class_name)s.allow_empty" ist False.',
    "Directory indexes are not allowed here.": "Verzeichnisindizes sind hier nicht erlaubt.",
    '"%(path)s" does not exist': '"%(path)s" existiert nicht',
    "Index of %(directory)s": "Verzeichnis von %(directory)s",
    "The install worked successfully! Congratulations!": "Die Installation war erfolgreich! Herzlichen Glückwunsch!",
    "Django Documentation": "Django-Dokumentation",
    "Topics, references, &amp; how-to's": "Themen, Referenzen &amp; Anleitungen",
    "Tutorial: A Polling App": "Tutorial: Eine Umfrage-App",
    "Get started with Django": "Erste Schritte mit Django",
    "Django Community": "Django-Community",
    "Connect, get help, or contribute": "Verbinden, Hilfe erhalten oder beitragen",

    # CKEditor / File upload
    "You do not have permission to upload files.": "Sie haben keine Berechtigung, Dateien hochzuladen.",
    "You must be logged in to upload files.": "Sie müssen angemeldet sein, um Dateien hochzuladen.",
    "File should be at most %(max_size)s MB.": "Datei sollte maximal %(max_size)s MB groß sein.",
    "Invalid form data": "Ungültige Formulardaten",
    "Check the correct settings.CKEDITOR_5_CONFIGS ": "Überprüfen Sie die korrekten settings.CKEDITOR_5_CONFIGS ",
    "Thumbnail": "Vorschaubild",

    # New template strings (from this session)
    "Confirm Logout": "Abmeldung bestätigen",
    "Are you sure you want to log out?": "Sind Sie sicher, dass Sie sich abmelden möchten?",
    "Logout": "Abmelden",
    "Close": "Schließen",
    "Back to top": "Nach oben",
    "Scroll to top": "Nach oben scrollen",

    # Activity levels page
    "Activity Levels": "Aktivitätsstufen",
    "Activity Points System": "Aktivitätspunkte-System",
    "Back to Profile": "Zurück zum Profil",
    "How Points are Calculated": "Wie Punkte berechnet werden",
    "Create a Post": "Einen Beitrag erstellen",
    "points": "Punkte",
    "Receive a Like": "Ein Like erhalten",
    "Write a Comment": "Einen Kommentar schreiben",
    "Daily Login": "Täglicher Login",
    "point": "Punkt",
    "ACHIEVEMENT LEVELS": "ERFOLGSSTUFEN",
    "Additional Information": "Zusätzliche Informationen",
    "Points are calculated automatically based on your activity.": "Punkte werden automatisch basierend auf Ihrer Aktivität berechnet.",
    "Your level is updated in real-time as you earn points.": "Ihre Stufe wird in Echtzeit aktualisiert, wenn Sie Punkte sammeln.",
    "All members start at Beginner level.": "Alle Mitglieder beginnen auf der Anfängerstufe.",
    "There is no penalty for inactivity.": "Es gibt keine Strafe für Inaktivität.",
    "Tips for Advancement": "Tipps zum Aufstieg",
    "Post regularly to the blog": "Regelmäßig im Blog posten",
    "Engage with other members' content": "Mit den Inhalten anderer Mitglieder interagieren",
    "Log in daily to earn bonus points": "Täglich einloggen, um Bonuspunkte zu verdienen",
    "Create quality content that others will like": "Qualitätsinhalte erstellen, die anderen gefallen",

    # Deactivate account
    "Deactivate Account": "Konto deaktivieren",
    "Warning:": "Warnung:",
    "Account deactivation is a serious action. Please read the information below carefully.": "Kontodeaktivierung ist eine schwerwiegende Aktion. Bitte lesen Sie die folgenden Informationen sorgfältig.",
    "What happens when you deactivate your account:": "Was passiert, wenn Sie Ihr Konto deaktivieren:",
    "Your profile will be hidden from other users": "Ihr Profil wird für andere Benutzer verborgen",
    "You will not be able to log in": "Sie können sich nicht mehr anmelden",
    "Your posts and comments will remain but show as anonymous": "Ihre Beiträge und Kommentare bleiben erhalten, werden aber als anonym angezeigt",
    "You can contact an administrator to reactivate your account": "Sie können einen Administrator kontaktieren, um Ihr Konto wieder zu aktivieren",
    "Yes, Deactivate My Account": "Ja, mein Konto deaktivieren",
    "Need help? Contact our support team before making this decision.": "Brauchen Sie Hilfe? Kontaktieren Sie unser Support-Team, bevor Sie diese Entscheidung treffen.",
    "Contact support": "Support kontaktieren",

    # Public profile (QR scan)
    "Public Profile": "Öffentliches Profil",
    "Active Member": "Aktives Mitglied",
    "Inactive": "Inaktiv",
    "Issued:": "Ausgestellt:",
    "For Partners:": "Für Partner:",
    "This member can use their IESA card for discounts and benefits at partner locations.": "Dieses Mitglied kann seine IESA-Karte für Rabatte und Vorteile bei Partnerstandorten verwenden.",

    # Log visit
    "Log Visit": "Besuch protokollieren",
    "Back to Dashboard": "Zurück zum Dashboard",
    "CHF": "CHF",
    "Member Verification Required": "Mitgliedsverifizierung erforderlich",
    "Ask the member to show their current 6-digit PIN from their personal cabinet.": "Bitten Sie das Mitglied, seine aktuelle 6-stellige PIN aus seinem persönlichen Bereich zu zeigen.",
    "Verify PIN & Log Visit": "PIN überprüfen & Besuch protokollieren",

    # Partner search
    "Results": "Ergebnisse",
    "No Results Found": "Keine Ergebnisse gefunden",
    "Try searching with a different name, username, or member ID.": "Versuchen Sie es mit einem anderen Namen, Benutzernamen oder Mitglieds-ID.",
    "Enter member name, username, or ID to search": "Mitgliedsname, Benutzername oder ID eingeben, um zu suchen",
}

# ============================================================
# FRENCH TRANSLATIONS
# ============================================================
FR = {
    # Events
    "Events": "Événements",
    "events": "événements",
    "gatherings": "rassemblements",
    "Date & time:": "Date et heure :",
    "Location:": "Lieu :",
    "DESCRIPTION": "DESCRIPTION",
    "Back to events": "Retour aux événements",
    "EVENTS CALENDAR": "CALENDRIER DES ÉVÉNEMENTS",
    "Upcoming Events & Gatherings": "Événements et rassemblements à venir",
    "Join us for exciting experiences and networking opportunities": "Rejoignez-nous pour des expériences passionnantes et des opportunités de réseautage",
    "Join to RSVP, comment and engage with members": "Inscrivez-vous pour participer, commenter et interagir avec les membres",
    "All posts": "Tous les articles",
    "Search events...": "Rechercher des événements...",
    "Search events": "Rechercher des événements",
    "Upcoming": "À venir",
    "All events": "Tous les événements",
    "Past": "Passés",
    "Date ↑": "Date ↑",
    "Date ↓": "Date ↓",
    "Title A→Z": "Titre A→Z",
    "Title Z→A": "Titre Z→A",
    "All categories": "Toutes les catégories",
    "Loading...": "Chargement...",
    "Back to blog": "Retour au blog",

    # Post creation
    "Create a new post": "Créer un nouvel article",
    "CREATE CONTENT": "CRÉER DU CONTENU",
    "Publish New Article or Announcement": "Publier un nouvel article ou une annonce",
    "Use our advanced editor: fonts, colors, lists, quotes and preview before publishing": "Utilisez notre éditeur avancé : polices, couleurs, listes, citations et aperçu avant publication",
    "Rich formatting: headings, lists, links, quotes, text and background colors.": "Formatage riche : titres, listes, liens, citations, couleurs de texte et d'arrière-plan.",
    "Preview": "Aperçu",
    "Create and submit for review": "Créer et soumettre pour révision",
    "Submitting...": "Soumission en cours...",
    "Live preview": "Aperçu en direct",
    "Preview image": "Image d'aperçu",
    "Add an image for preview": "Ajouter une image pour l'aperçu",
    "Draft preview": "Aperçu du brouillon",
    "Post Title": "Titre de l'article",
    "Description will appear here after editing.": "La description apparaîtra ici après modification.",
    "Please enter a post title": "Veuillez entrer un titre d'article",
    "Please enter post content": "Veuillez entrer le contenu de l'article",

    # Blog / Comments
    "Anonymous": "Anonyme",
    "views": "vues",
    "COMMENTS": "COMMENTAIRES",
    "Leave a comment": "Laisser un commentaire",
    "Your comment...": "Votre commentaire...",
    "Send": "Envoyer",
    "To comment, please": "Pour commenter, veuillez",
    "sign in": "vous connecter",
    "or": "ou",
    "register": "vous inscrire",
    "RECOMMENDED POSTS": "ARTICLES RECOMMANDÉS",
    "Community & Blog": "Communauté & Blog",
    "COMMUNITY": "COMMUNAUTÉ",
    "Share Ideas, Events & News": "Partagez vos idées, événements et actualités",
    "Sign in or register to access the community": "Connectez-vous ou inscrivez-vous pour accéder à la communauté",
    "Join our community to create posts, comment and engage with members": "Rejoignez notre communauté pour créer des articles, commenter et interagir avec les membres",
    "All Posts": "Tous les articles",
    "Search posts...": "Rechercher des articles...",
    "Search posts": "Rechercher des articles",
    "All statuses": "Tous les statuts",
    "Published": "Publié",
    "Pending": "En attente",
    "Latest": "Récents",
    "Popular": "Populaires",
    "Trending": "Tendances",
    "Create Post": "Créer un article",
    "No Posts Yet": "Pas encore d'articles",
    "Be the first to share news or ideas with the community": "Soyez le premier à partager des nouvelles ou des idées avec la communauté",
    "Create First Post": "Créer le premier article",
    "Join Community": "Rejoindre la communauté",

    # Benefits
    "Member Benefits": "Avantages membres",
    "IESA Member Benefits": "Avantages membres IESA",
    "Get exclusive discounts and benefits as a member of our association": "Obtenez des réductions et avantages exclusifs en tant que membre de notre association",
    "Terms of access": "Conditions d'accès",
    "Want access to these benefits?": "Vous voulez accéder à ces avantages ?",
    "Become an IESA member and receive exclusive discounts and privileges": "Devenez membre de l'IESA et recevez des réductions et privilèges exclusifs",
    "Join now": "Rejoindre maintenant",
    "Back to home": "Retour à l'accueil",
    "Benefits coming soon": "Avantages à venir",
    "We are working on exclusive offers for our members": "Nous travaillons sur des offres exclusives pour nos membres",

    # Partners / Teams
    "Teams": "Équipes",
    "Teams · Corporate": "Équipes · Entreprises",
    "Sponsor": "Parrain",
    "Partner": "Partenaire",
    "Details": "Détails",

    # Gallery
    "PHOTO GALLERY": "GALERIE PHOTO",
    "Moments From Our Community": "Moments de notre communauté",
    "See how we work, train and create memories together": "Découvrez comment nous travaillons, nous entraînons et créons des souvenirs ensemble",
    "Photo": "Photo",
    "View photo": "Voir la photo",
    "Previous": "Précédent",
    "Next": "Suivant",
    "No photos yet": "Pas encore de photos",
    "Add photos from events or projects to inspire members.": "Ajoutez des photos d'événements ou de projets pour inspirer les membres.",
    "Go to community": "Aller à la communauté",

    # Messaging
    "Chat with %(first)s %(last)s": "Discussion avec %(first)s %(last)s",
    "Profile": "Profil",
    "Search": "Recherche",
    "%(name)s is typing": "%(name)s est en train d'écrire",
    "Type a message...": "Écrire un message...",
    "Attach file": "Joindre un fichier",
    "Search messages": "Rechercher des messages",
    "Search...": "Rechercher...",
    "Edit": "Modifier",
    "Delete": "Supprimer",
    "Today": "Aujourd'hui",
    "Yesterday": "Hier",
    "(edited)": "(modifié)",
    "Edit message:": "Modifier le message :",
    "Delete message?": "Supprimer le message ?",
    "No results found": "Aucun résultat trouvé",
    "Messages": "Messages",
    "New chat": "Nouvelle discussion",
    "Search chats...": "Rechercher des discussions...",
    "No chats": "Aucune discussion",
    "Select a chat": "Sélectionner une discussion",
    "Or start a new conversation": "Ou commencer une nouvelle conversation",
    "Search users...": "Rechercher des utilisateurs...",
    "Type a name to search": "Tapez un nom pour rechercher",
    "No messages": "Aucun message",
    "No users found": "Aucun utilisateur trouvé",

    # Notifications
    "Notifications": "Notifications",
    "Stay updated with your activity": "Restez informé de votre activité",
    "Mark all as read": "Tout marquer comme lu",
    "Unread": "Non lu",
    "All notifications marked as read": "Toutes les notifications marquées comme lues",
    "New": "Nouveau",
    "ago": "il y a",
    "View": "Voir",
    "Delete notification": "Supprimer la notification",
    "Notifications pagination": "Pagination des notifications",
    "No notifications yet": "Pas encore de notifications",
    "You'll see notifications here when someone interacts with your content.": "Vous verrez les notifications ici quand quelqu'un interagit avec votre contenu.",
    "Explore Posts": "Explorer les articles",

    # Error pages
    "404 - Page not found": "404 – Page non trouvée",
    "Page not found": "Page non trouvée",
    "Maybe you were looking for:": "Peut-être cherchiez-vous :",
    "Search the site...": "Rechercher sur le site...",
    "500 - Internal server error": "500 – Erreur interne du serveur",
    "Internal server error": "Erreur interne du serveur",
    "Go back": "Retour",
    "If the problem persists, please contact our support team.": "Si le problème persiste, veuillez contacter notre équipe d'assistance.",

    # Base / Navigation
    "IESA ROOT": "IESA ROOT",
    "Skip to main content": "Aller au contenu principal",
    "Attention!": "Attention !",
    "Site is under active development. Some features may not work correctly.": "Le site est en cours de développement. Certaines fonctionnalités peuvent ne pas fonctionner correctement.",
    "Main navigation": "Navigation principale",
    "IESA Home": "Accueil IESA",
    "IESA Logo": "Logo IESA",
    "Toggle navigation": "Basculer la navigation",
    "IESA Association. All rights reserved.": "Association IESA. Tous droits réservés.",
    "LINKS": "LIENS",
    "CONTACTS": "CONTACTS",
    "SOCIAL": "RÉSEAUX SOCIAUX",

    # Model fields
    "Permanent ID": "ID permanent",
    "Card active": "Carte active",
    "Card issued at": "Carte émise le",
    "Membership Status": "Statut d'adhésion",
    "TOTP Secret": "Secret TOTP",
    "Pseudonym": "Pseudonyme",
    "User Account": "Compte utilisateur",
    "Company Name": "Nom de l'entreprise",
    "Business Type": "Type d'activité",
    "Created At": "Créé le",
    "Member": "Membre",
    "Service Type": "Type de service",
    "Service Description": "Description du service",
    "Cost": "Coût",
    "Comments": "Commentaires",
    "PIN Verified": "PIN vérifié",
    "Visit Time": "Heure de visite",
    "Visits": "Visites",

    # Login
    "Welcome back": "Bon retour",
    "Sign in to manage your profile, create posts and discover events.": "Connectez-vous pour gérer votre profil, créer des articles et découvrir des événements.",
    "Quick Access": "Accès rapide",
    "Community Engagement": "Engagement communautaire",
    "Event Updates": "Mises à jour des événements",
    "SIGN IN": "SE CONNECTER",
    "Access your profile and connect with the community.": "Accédez à votre profil et connectez-vous avec la communauté.",
    "Sign in failed!": "Échec de la connexion !",
    "Invalid username or password. Please try again.": "Nom d'utilisateur ou mot de passe invalide. Veuillez réessayer.",
    "Don't have an account?": "Vous n'avez pas de compte ?",
    "Register here": "Inscrivez-vous ici",

    # Profile
    "Profile of %(username)s": "Profil de %(username)s",
    "Edit Profile": "Modifier le profil",
    "Your QR Code": "Votre code QR",
    "Open profile by card": "Ouvrir le profil par carte",
    "QR Code": "Code QR",
    "Scan to view profile": "Scanner pour voir le profil",
    "Download QR": "Télécharger le QR",
    "Follow": "Suivre",
    "Sign in": "Se connecter",
    "to follow users": "pour suivre des utilisateurs",
    "Full name": "Nom complet",
    "Date of birth": "Date de naissance",
    "years": "ans",
    "Phone": "Téléphone",
    "Hidden": "Masqué",
    "Not specified": "Non spécifié",
    "Joined": "Inscrit",
    "Activity Level": "Niveau d'activité",
    "Legend": "Légende",
    "Expert": "Expert",
    "Advanced": "Avancé",
    "Intermediate": "Intermédiaire",
    "Beginner": "Débutant",
    "Learn about activity levels": "En savoir plus sur les niveaux d'activité",
    "Activity Points": "Points d'activité",
    "Progress to %(level)s:": "Progression vers %(level)s :",
    "Maximum level achieved!": "Niveau maximum atteint !",
    "Find me": "Me trouver",
    "Total posts": "Total des articles",
    "Likes received": "Likes reçus",
    "Comments made": "Commentaires faits",
    "Your Posts": "Vos articles",
    "Title": "Titre",
    "Status": "Statut",
    "Created": "Créé",
    "Actions": "Actions",
    "Rejected": "Rejeté",
    "You have no posts yet.": "Vous n'avez pas encore d'articles.",
    "Create your first post": "Créez votre premier article",

    # Edit profile
    "Edit profile": "Modifier le profil",
    "Refresh your info, avatar and social links.": "Mettez à jour vos informations, avatar et liens sociaux.",
    "Basic info": "Informations de base",
    "First name": "Prénom",
    "Last name": "Nom de famille",
    "Email": "E-mail",
    "Format: DD.MM.YYYY": "Format : JJ.MM.AAAA",
    "Phone Number": "Numéro de téléphone",
    "Example: +41 XX XXX XX XX": "Exemple : +41 XX XXX XX XX",
    "Hide phone number (only admins can see it)": "Masquer le numéro de téléphone (seuls les admins peuvent le voir)",
    "Avatar": "Avatar",
    "Upload square image for best fit.": "Téléchargez une image carrée pour un meilleur rendu.",
    "Social & links": "Réseaux sociaux & liens",
    "examples below": "exemples ci-dessous",
    "Other links": "Autres liens",
    "one per line": "un par ligne",
    "Save changes": "Enregistrer les modifications",
    "Cancel": "Annuler",

    # Public profile
    "Member since": "Membre depuis",
    "Copy ID": "Copier l'ID",
    "Verified": "Vérifié",
    "Card Active": "Carte active",
    "Activity Statistics": "Statistiques d'activité",
    "Posts": "Articles",
    "Likes": "Likes",
    "Admin Panel": "Panneau d'administration",
    "Links": "Liens",
    "Website": "Site web",
    "Other:": "Autres :",
    "Published Posts": "Articles publiés",
    "No published posts yet.": "Pas encore d'articles publiés.",
    "About": "À propos",

    # Registration
    "Join IESA Today": "Rejoignez l'IESA aujourd'hui",
    "Connect with Athletes": "Connectez-vous avec des athlètes",
    "Share Your Journey": "Partagez votre parcours",
    "Discover Events": "Découvrir des événements",
    "Build Your Profile": "Créer votre profil",
    "REGISTER": "S'INSCRIRE",
    "Join the IESA community and start sharing!": "Rejoignez la communauté IESA et commencez à partager !",
    "Registration failed:": "Échec de l'inscription :",
    "Create Account": "Créer un compte",
    "Already have an account?": "Vous avez déjà un compte ?",
    "Sign in here": "Connectez-vous ici",

    # Member directory
    "User search": "Recherche d'utilisateur",
    "MEMBER DIRECTORY": "ANNUAIRE DES MEMBRES",
    "Find & Connect With Members": "Trouver et contacter des membres",
    "Search our community by name, username, email or ID": "Recherchez dans notre communauté par nom, pseudo, e-mail ou ID",
    "Search by name, username, email or ID...": "Rechercher par nom, pseudo, e-mail ou ID...",
    "Results for": "Résultats pour",
    "No users found.": "Aucun utilisateur trouvé.",

    # Validation
    "Password must contain at least one uppercase letter (A-Z).": "Le mot de passe doit contenir au moins une lettre majuscule (A-Z).",
    "Your password must contain at least one uppercase letter (A-Z).": "Votre mot de passe doit contenir au moins une lettre majuscule (A-Z).",
    "Некорректный номер телефона. Допустимы цифры, пробелы, '+', '-', '()'.": "Numéro de téléphone invalide. Chiffres, espaces, '+', '-', '()' sont autorisés.",
    "Введите корректное имя Discord (например: username или username#1234)": "Entrez un nom Discord valide (par exemple : username ou username#1234)",

    # Django framework
    "Site Maps": "Plans de site",
    "Static Files": "Fichiers statiques",
    "Syndication": "Syndication",
    "…": "…",
    "That page number is not an integer": "Ce numéro de page n'est pas un entier",
    "That page number is less than 1": "Ce numéro de page est inférieur à 1",
    "That page contains no results": "Cette page ne contient aucun résultat",
    "Enter a valid value.": "Saisissez une valeur valide.",
    "Enter a valid domain name.": "Saisissez un nom de domaine valide.",
    "Enter a valid URL.": "Saisissez une URL valide.",
    "Enter a valid integer.": "Saisissez un nombre entier valide.",
    "Enter a valid email address.": "Saisissez une adresse e-mail valide.",
    "Enter a valid %(protocol)s address.": "Saisissez une adresse %(protocol)s valide.",
    "IPv4": "IPv4",
    "IPv6": "IPv6",
    "IPv4 or IPv6": "IPv4 ou IPv6",
    "Enter only digits separated by commas.": "Saisissez uniquement des chiffres séparés par des virgules.",
    "Ensure this value is %(limit_value)s (it is %(show_value)s).": "Assurez-vous que cette valeur est %(limit_value)s (elle est %(show_value)s).",
    "Ensure this value is less than or equal to %(limit_value)s.": "Assurez-vous que cette valeur est inférieure ou égale à %(limit_value)s.",
    "Ensure this value is greater than or equal to %(limit_value)s.": "Assurez-vous que cette valeur est supérieure ou égale à %(limit_value)s.",
    "Ensure this value is a multiple of step size %(limit_value)s.": "Assurez-vous que cette valeur est un multiple du pas %(limit_value)s.",
    "Enter a number.": "Saisissez un nombre.",
    "Null characters are not allowed.": "Les caractères nuls ne sont pas autorisés.",
    "and": "et",
    "%(model_name)s with this %(field_labels)s already exists.": "%(model_name)s avec ce %(field_labels)s existe déjà.",
    'Constraint "%(name)s" is violated.': 'La contrainte "%(name)s" est violée.',
    "Value %(value)r is not a valid choice.": "La valeur %(value)r n'est pas un choix valide.",
    "This field cannot be null.": "Ce champ ne peut pas être nul.",
    "This field cannot be blank.": "Ce champ ne peut pas être vide.",
    "%(model_name)s with this %(field_label)s already exists.": "%(model_name)s avec ce %(field_label)s existe déjà.",
    "Field of type: %(field_type)s": "Champ de type : %(field_type)s",
    '"%(value)s" value must be either True or False.': 'La valeur "%(value)s" doit être True ou False.',
    '"%(value)s" value must be either True, False, or None.': 'La valeur "%(value)s" doit être True, False ou None.',
    "Boolean (Either True or False)": "Booléen (True ou False)",
    "String (up to %(max_length)s)": "Chaîne (jusqu'à %(max_length)s)",
    "String (unlimited)": "Chaîne (illimitée)",
    "Comma-separated integers": "Entiers séparés par des virgules",
    "Date (without time)": "Date (sans heure)",
    "Date (with time)": "Date (avec heure)",
    '"%(value)s" value must be a decimal number.': 'La valeur "%(value)s" doit être un nombre décimal.',
    "Decimal number": "Nombre décimal",
    "Duration": "Durée",
    "Email address": "Adresse e-mail",
    "File path": "Chemin du fichier",
    '"%(value)s" value must be a float.': 'La valeur "%(value)s" doit être un nombre à virgule flottante.',
    "Floating point number": "Nombre à virgule flottante",
    '"%(value)s" value must be an integer.': 'La valeur "%(value)s" doit être un entier.',
    "Integer": "Entier",
    "Big (8 byte) integer": "Grand entier (8 octets)",
    "Small integer": "Petit entier",
    "IPv4 address": "Adresse IPv4",
    "IP address": "Adresse IP",
    '"%(value)s" value must be either None, True or False.': 'La valeur "%(value)s" doit être None, True ou False.',
    "Boolean (Either True, False or None)": "Booléen (True, False ou None)",
    "Positive big integer": "Grand entier positif",
    "Positive integer": "Entier positif",
    "Positive small integer": "Petit entier positif",
    "Slug (up to %(max_length)s)": "Slug (jusqu'à %(max_length)s)",
    "Text": "Texte",
    "Time": "Heure",
    "URL": "URL",
    "Raw binary data": "Données binaires brutes",
    '"%(value)s" is not a valid UUID.': '"%(value)s" n\'est pas un UUID valide.',
    "Universally unique identifier": "Identifiant unique universel",
    "File": "Fichier",
    "Image": "Image",
    "A JSON object": "Un objet JSON",
    "Value must be valid JSON.": "La valeur doit être du JSON valide.",
    "%(model)s instance with %(field)s %(value)r is not a valid choice.": "L'instance %(model)s avec %(field)s %(value)r n'est pas un choix valide.",
    "Foreign Key (type determined by related field)": "Clé étrangère (type déterminé par le champ lié)",
    "One-to-one relationship": "Relation un-à-un",
    "%(from)s-%(to)s relationship": "Relation %(from)s-%(to)s",
    "%(from)s-%(to)s relationships": "Relations %(from)s-%(to)s",
    "Many-to-many relationship": "Relation plusieurs-à-plusieurs",
    ":?.!": ":?.!",
    "This field is required.": "Ce champ est obligatoire.",
    "Enter a whole number.": "Saisissez un nombre entier.",
    "Enter a valid date.": "Saisissez une date valide.",
    "Enter a valid time.": "Saisissez une heure valide.",
    "Enter a valid date/time.": "Saisissez une date/heure valide.",
    "Enter a valid duration.": "Saisissez une durée valide.",
    "The number of days must be between {min_days} and {max_days}.": "Le nombre de jours doit être entre {min_days} et {max_days}.",
    "No file was submitted. Check the encoding type on the form.": "Aucun fichier soumis. Vérifiez le type d'encodage du formulaire.",
    "No file was submitted.": "Aucun fichier soumis.",
    "The submitted file is empty.": "Le fichier soumis est vide.",
    "Please either submit a file or check the clear checkbox, not both.": "Veuillez soumettre un fichier ou cocher la case d'effacement, pas les deux.",
    "Select a valid choice. %(value)s is not one of the available choices.": "Sélectionnez un choix valide. %(value)s n'est pas parmi les choix disponibles.",
    "Enter a list of values.": "Saisissez une liste de valeurs.",
    "Enter a complete value.": "Saisissez une valeur complète.",
    "Enter a valid UUID.": "Saisissez un UUID valide.",
    "Enter a valid JSON.": "Saisissez du JSON valide.",
    ":": ":",
    "(Hidden field %(name)s) %(error)s": "(Champ masqué %(name)s) %(error)s",
    "Order": "Ordre",
    "Please correct the duplicate data for %(field)s.": "Veuillez corriger les données en double pour %(field)s.",
    "Please correct the duplicate data for %(field)s, which must be unique.": "Veuillez corriger les données en double pour %(field)s, qui doivent être uniques.",
    "Please correct the duplicate values below.": "Veuillez corriger les valeurs en double ci-dessous.",
    "The inline value did not match the parent instance.": "La valeur en ligne ne correspondait pas à l'instance parente.",
    "Select a valid choice. That choice is not one of the available choices.": "Sélectionnez un choix valide. Ce choix n'est pas disponible.",
    '"%(pk)s" is not a valid value.': '"%(pk)s" n\'est pas une valeur valide.',
    "Clear": "Effacer",
    "Currently": "Actuellement",
    "Change": "Modifier",
    "Unknown": "Inconnu",
    "Yes": "Oui",
    "No": "Non",
    "yes,no,maybe": "oui,non,peut-être",

    # File sizes
    "%s KB": "%s Ko",
    "%s MB": "%s Mo",
    "%s GB": "%s Go",
    "%s TB": "%s To",
    "%s PB": "%s Po",

    # Time
    "p.m.": "après-midi",
    "a.m.": "matin",
    "PM": "PM",
    "AM": "AM",
    "midnight": "minuit",
    "noon": "midi",

    # Days
    "Monday": "Lundi",
    "Tuesday": "Mardi",
    "Wednesday": "Mercredi",
    "Thursday": "Jeudi",
    "Friday": "Vendredi",
    "Saturday": "Samedi",
    "Sunday": "Dimanche",
    "Mon": "Lun",
    "Tue": "Mar",
    "Wed": "Mer",
    "Thu": "Jeu",
    "Fri": "Ven",
    "Sat": "Sam",
    "Sun": "Dim",

    # Months
    "January": "Janvier",
    "February": "Février",
    "March": "Mars",
    "April": "Avril",
    "May": "Mai",
    "June": "Juin",
    "July": "Juillet",
    "August": "Août",
    "September": "Septembre",
    "October": "Octobre",
    "November": "Novembre",
    "December": "Décembre",

    # Months abbreviated
    "jan": "jan",
    "feb": "fév",
    "mar": "mar",
    "apr": "avr",
    "may": "mai",
    "jun": "jun",
    "jul": "jul",
    "aug": "aoû",
    "sep": "sep",
    "oct": "oct",
    "nov": "nov",
    "dec": "déc",
    "Jan.": "Jan.",
    "Feb.": "Fév.",
    "Aug.": "Aoû.",
    "Sept.": "Sep.",
    "Oct.": "Oct.",
    "Nov.": "Nov.",
    "Dec.": "Déc.",

    # More Django framework
    "This is not a valid IPv6 address.": "Ceci n'est pas une adresse IPv6 valide.",
    "%(truncated_text)s…": "%(truncated_text)s…",
    ", ": ", ",
    "Forbidden": "Interdit",
    "CSRF verification failed. Request aborted.": "La vérification CSRF a échoué. Requête annulée.",
    "More information is available with DEBUG=True.": "Plus d'informations disponibles avec DEBUG=True.",
    "No year specified": "Aucune année spécifiée",
    "Date out of range": "Date hors limites",
    "No month specified": "Aucun mois spécifié",
    "No day specified": "Aucun jour spécifié",
    "No week specified": "Aucune semaine spécifiée",
    "No %(verbose_name_plural)s available": "Aucun %(verbose_name_plural)s disponible",
    'Invalid date string "%(datestr)s" given format "%(format)s"': 'Chaîne de date invalide "%(datestr)s" pour le format "%(format)s"',
    "No %(verbose_name)s found matching the query": "Aucun %(verbose_name)s trouvé correspondant à la requête",
    'Page is not "last", nor can it be converted to an int.': 'La page n\'est pas "last" et ne peut pas être convertie en entier.',
    "Invalid page (%(page_number)s): %(message)s": "Page invalide (%(page_number)s) : %(message)s",
    'Empty list and "%(class_name)s.allow_empty" is False.': 'Liste vide et "%(class_name)s.allow_empty" est False.',
    "Directory indexes are not allowed here.": "Les index de répertoire ne sont pas autorisés ici.",
    '"%(path)s" does not exist': '"%(path)s" n\'existe pas',
    "Index of %(directory)s": "Index de %(directory)s",
    "The install worked successfully! Congratulations!": "L'installation a réussi ! Félicitations !",
    "Django Documentation": "Documentation Django",
    "Topics, references, &amp; how-to's": "Sujets, références et tutoriels",
    "Tutorial: A Polling App": "Tutoriel : une application de sondage",
    "Get started with Django": "Débuter avec Django",
    "Django Community": "Communauté Django",
    "Connect, get help, or contribute": "Se connecter, obtenir de l'aide ou contribuer",

    # CKEditor
    "You do not have permission to upload files.": "Vous n'avez pas la permission de télécharger des fichiers.",
    "You must be logged in to upload files.": "Vous devez être connecté pour télécharger des fichiers.",
    "File should be at most %(max_size)s MB.": "Le fichier doit faire au maximum %(max_size)s Mo.",
    "Invalid form data": "Données de formulaire invalides",
    "Check the correct settings.CKEDITOR_5_CONFIGS ": "Vérifiez les paramètres corrects settings.CKEDITOR_5_CONFIGS ",
    "Thumbnail": "Miniature",

    # New template strings
    "Confirm Logout": "Confirmer la déconnexion",
    "Are you sure you want to log out?": "Êtes-vous sûr de vouloir vous déconnecter ?",
    "Logout": "Déconnexion",
    "Close": "Fermer",
    "Back to top": "Retour en haut",
    "Scroll to top": "Retour en haut de page",

    # Activity levels page
    "Activity Levels": "Niveaux d'activité",
    "Activity Points System": "Système de points d'activité",
    "Back to Profile": "Retour au profil",
    "How Points are Calculated": "Comment les points sont calculés",
    "Create a Post": "Créer un article",
    "points": "points",
    "Receive a Like": "Recevoir un Like",
    "Write a Comment": "Écrire un commentaire",
    "Daily Login": "Connexion quotidienne",
    "point": "point",
    "ACHIEVEMENT LEVELS": "NIVEAUX DE RÉUSSITE",
    "Additional Information": "Informations supplémentaires",
    "Points are calculated automatically based on your activity.": "Les points sont calculés automatiquement en fonction de votre activité.",
    "Your level is updated in real-time as you earn points.": "Votre niveau est mis à jour en temps réel au fur et à mesure que vous gagnez des points.",
    "All members start at Beginner level.": "Tous les membres commencent au niveau Débutant.",
    "There is no penalty for inactivity.": "Il n'y a pas de pénalité pour l'inactivité.",
    "Tips for Advancement": "Conseils pour progresser",
    "Post regularly to the blog": "Publiez régulièrement sur le blog",
    "Engage with other members' content": "Interagissez avec le contenu des autres membres",
    "Log in daily to earn bonus points": "Connectez-vous quotidiennement pour gagner des points bonus",
    "Create quality content that others will like": "Créez du contenu de qualité que les autres aimeront",

    # Deactivate account
    "Deactivate Account": "Désactiver le compte",
    "Warning:": "Avertissement :",
    "Account deactivation is a serious action. Please read the information below carefully.": "La désactivation du compte est une action sérieuse. Veuillez lire attentivement les informations ci-dessous.",
    "What happens when you deactivate your account:": "Ce qui se passe quand vous désactivez votre compte :",
    "Your profile will be hidden from other users": "Votre profil sera masqué des autres utilisateurs",
    "You will not be able to log in": "Vous ne pourrez plus vous connecter",
    "Your posts and comments will remain but show as anonymous": "Vos articles et commentaires resteront mais seront affichés comme anonymes",
    "You can contact an administrator to reactivate your account": "Vous pouvez contacter un administrateur pour réactiver votre compte",
    "Yes, Deactivate My Account": "Oui, désactiver mon compte",
    "Need help? Contact our support team before making this decision.": "Besoin d'aide ? Contactez notre équipe d'assistance avant de prendre cette décision.",
    "Contact support": "Contacter le support",

    # Public profile (QR scan)
    "Public Profile": "Profil public",
    "Active Member": "Membre actif",
    "Inactive": "Inactif",
    "Issued:": "Émis :",
    "For Partners:": "Pour les partenaires :",
    "This member can use their IESA card for discounts and benefits at partner locations.": "Ce membre peut utiliser sa carte IESA pour des réductions et avantages chez les partenaires.",

    # Log visit
    "Log Visit": "Enregistrer la visite",
    "Back to Dashboard": "Retour au tableau de bord",
    "CHF": "CHF",
    "Member Verification Required": "Vérification du membre requise",
    "Ask the member to show their current 6-digit PIN from their personal cabinet.": "Demandez au membre de montrer son code PIN à 6 chiffres depuis son espace personnel.",
    "Verify PIN & Log Visit": "Vérifier le PIN et enregistrer la visite",

    # Partner search
    "Results": "Résultats",
    "No Results Found": "Aucun résultat trouvé",
    "Try searching with a different name, username, or member ID.": "Essayez de rechercher avec un autre nom, pseudo ou ID de membre.",
    "Enter member name, username, or ID to search": "Entrez le nom, le pseudo ou l'ID du membre pour rechercher",
}


def translate_po(filepath, translations):
    """Replace msgstr entries that match their msgid with proper translations."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    count = 0
    for msgid, translation in translations.items():
        if msgid == translation:
            continue  # Skip if translation is same as source
        # Escape for .po format
        escaped_msgid = msgid.replace('\\', '\\\\').replace('"', '\\"')
        escaped_translation = translation.replace('\\', '\\\\').replace('"', '\\"')

        old = f'msgid "{escaped_msgid}"\nmsgstr "{escaped_msgid}"'
        new = f'msgid "{escaped_msgid}"\nmsgstr "{escaped_translation}"'

        if old in content:
            content = content.replace(old, new, 1)
            count += 1

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    return count


if __name__ == '__main__':
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    de_path = os.path.join(base, 'locale', 'de', 'LC_MESSAGES', 'django.po')
    fr_path = os.path.join(base, 'locale', 'fr', 'LC_MESSAGES', 'django.po')

    de_count = translate_po(de_path, DE)
    print(f"DE: Translated {de_count} entries")

    fr_count = translate_po(fr_path, FR)
    print(f"FR: Translated {fr_count} entries")
