"""FastAPI/deps.py — dependency injection: database connection + Telegram auth.

Two auth flows are supported:
  x-init-data      — Telegram WebApp (opened inside Telegram)
  x-session-token  — Login Widget session (opened in a regular browser)
"""
import asyncio
import json
import os
import time
from urllib.parse import unquote

from fastapi import Depends, Header, HTTPException, Request
from infrastructure.database import create_pool, get_pool
from infrastructure.pg_adapter import PGAdapter
from FastAPI.auth import (verify_preprod_browser_ticket, verify_webapp_data,
                          verify_session_token, hash_signal)
from infrastructure.preprod import is_preprod, is_preprod_browser_test_user, require_preprod_user


_SITE_OPEN = os.getenv("SITE_OPEN_TO_PLAYERS", "").strip().lower() in ("1", "true", "yes")
_DEV_ID = int(os.getenv("DEVELOPER_ID", "0") or 0)
_PREPROD_TEST_COOKIE = "predvestnik_preprod_test_session"


async def get_db():
    """Yield a PGAdapter-wrapped DB connection from the shared pool.

    If the shared pool has not been initialized yet, create it lazily.
    This protects FastAPI requests that arrive before the bot process finishes
    its startup sequence and global DB initialization.
    """
    await create_pool()
    async with get_pool().acquire() as conn:
        yield PGAdapter(conn)


async def require_tg_user_base(
    request: Request,
    x_init_data: str = Header(default=""),
    x_session_token: str = Header(default=""),
    x_preprod_browser_ticket: str = Header(default=""),
    x_client_fp: str = Header(default=""),
):
    """Auth БЕЗ проверки глобального бана — ТОЛЬКО для эндпоинтов, которые обязаны
    работать у забаненных (апелляции: admin_audit B1 — оспорить можно в любой
    момент и любым способом). Везде остальное — require_tg_user."""
    user = None
    # 1. Telegram WebApp (in-Telegram button)
    if x_init_data:
        user = verify_webapp_data(x_init_data)

    # 2. Local automation persona. This cookie can only be issued by a
    # second Uvicorn listener bound to 127.0.0.1, and is rejected everywhere
    # except isolated preprod. It intentionally wins over a stale browser
    # session header, but never over genuine Telegram initData above.
    # Do not turn this into a production fallback.
    local_test_persona = False
    if not user and is_preprod():
        test_user_id = verify_session_token(request.cookies.get(_PREPROD_TEST_COOKIE, ""))
        if test_user_id and is_preprod_browser_test_user(test_user_id):
            user = {"id": test_user_id, "preprod_test_persona": True}
            local_test_persona = True

    # The visible browser automation surface can partition a localhost cookie
    # when it follows the 8404 -> 8403 redirect.  It receives only a short,
    # purpose-bound test ticket generated by the loopback listener; regular
    # clients never send this header and no real Telegram identity is accepted.
    if not user and is_preprod() and x_preprod_browser_ticket:
        test_user_id = verify_preprod_browser_ticket(x_preprod_browser_ticket)
        if test_user_id and is_preprod_browser_test_user(test_user_id):
            user = {"id": test_user_id, "preprod_test_persona": True}
            local_test_persona = True

    # 3. Login Widget session (browser)
    if not user and x_session_token:
        user_id = verify_session_token(x_session_token)
        if user_id:
            user = {"id": user_id}

    if not user:
        raise HTTPException(
            status_code=401,
            detail="Требуется авторизация через Telegram.",
        )
    if not local_test_persona and not require_preprod_user(int(user["id"])):
        # A Quick Tunnel is public by design; only explicitly listed test
        # accounts may mutate the isolated preprod database.
        raise HTTPException(status_code=403, detail="Тестовый стенд закрыт для этого аккаунта.")
    # Сайт закрыт для игроков: пускаем только разработчика. Открыть обратно —
    # переменная окружения SITE_OPEN_TO_PLAYERS=1.
    if not _SITE_OPEN and not (_DEV_ID and int(user["id"]) == _DEV_ID):
        raise HTTPException(status_code=503, detail="Сайт временно закрыт: идёт переработка. Скоро вернёмся.")
    _fire_and_forget(_capture_signals(int(user["id"]), request, x_client_fp))
    return user


# ── Твинк-детект (dev-console, диагностика без наказаний) ───────────────────────
# Пишем солёные HMAC-хэши IP/отпечатка устройства (не сырые значения — auth.hash_signal),
# с троттлингом в памяти, иначе десятки API-запросов на загрузку страницы = столько же
# INSERT'ов на каждого юзера. См. services/twin_detection.py — сам скоринг пар.
_SIGNAL_SEEN: dict[tuple, float] = {}
_SIGNAL_SEEN_TTL = 1800.0  # 30 минут между записями одного и того же сигнала
_BG_TASKS: set = set()


def _fire_and_forget(coro) -> None:
    """asyncio.create_task без хранения ссылки рискует потерять задачу к GC —
    держим её в сете до завершения."""
    task = asyncio.create_task(coro)
    _BG_TASKS.add(task)
    task.add_done_callback(_BG_TASKS.discard)


def _client_ip(request: Request) -> str:
    fwd = request.headers.get("x-forwarded-for", "")
    if fwd:
        return fwd.split(",")[0].strip()
    return request.client.host if request.client else ""


async def _capture_signals(user_id: int, request: Request, client_fp: str) -> None:
    try:
        now = time.monotonic()
        raw_pairs = []
        ip = _client_ip(request)
        if ip:
            raw_pairs.append(("ip", hash_signal(ip)))
        if client_fp:
            raw_pairs.append(("fp", hash_signal(client_fp)))
        to_write = []
        for kind, vhash in raw_pairs:
            if not vhash:
                continue
            key = (user_id, kind, vhash)
            hit = _SIGNAL_SEEN.get(key)
            if hit and hit > now:
                continue
            _SIGNAL_SEEN[key] = now + _SIGNAL_SEEN_TTL
            to_write.append((kind, vhash))
        if not to_write:
            return
        if len(_SIGNAL_SEEN) > 50000:   # страховка от разрастания
            _SIGNAL_SEEN.clear()
        await create_pool()
        from infrastructure.repositories import twin_signals
        async with get_pool().acquire() as conn:
            db = PGAdapter(conn)
            for kind, vhash in to_write:
                await twin_signals.record(db, user_id, kind, vhash)
    except Exception:
        pass


async def require_tg_user(user=Depends(require_tg_user_base), db=Depends(get_db)):
    """Auth + account-deletion gate for the whole gameplay API."""
    async with db.execute(
        "SELECT deleted_at FROM users WHERE user_tg_id=?", (int(user["id"]),)
    ) as cursor:
        account = await cursor.fetchone()
    if account and account[0] is not None:
        raise HTTPException(
            status_code=403,
            detail="ACCOUNT_DELETED: игровые действия закрыты до восстановления аккаунта.",
        )
    return user


def require_module(module_key: str):
    """FastAPI dependency factory: checks per-chat and global module toggles.

    chat_id source (priority order):
      1. initData 'chat' field (Telegram-signed, present only when opened from a group)
      2. x-chat-id header (fallback for Login Widget browser sessions)

    Skips per-chat check when no chat_id is known.
    Always performs the global check via global_module_toggles.

    DEVELOPER_ID обходит любой тумблер (страховка та же, что в _actor_global_rank
    выше) — иначе разработчик не может зайти и проверить/включить обратно
    раздел, который сам же выключил для теста (жалоба владельца 2026-07-29:
    "почему разделы отключаются и для разработчика")."""
    async def _check(
        x_init_data: str = Header(default=""),
        x_chat_id: int = Header(default=0),
        db=Depends(get_db),
        user=Depends(require_tg_user_base),
    ):
        if _DEV_ID and int(user["id"]) == _DEV_ID:
            return
        # Extract chat_id from Telegram-signed initData
        chat_id = 0
        if x_init_data:
            try:
                params: dict[str, str] = {}
                for part in x_init_data.split("&"):
                    if "=" in part:
                        k, v = part.split("=", 1)
                        params[k] = unquote(v)
                chat_str = params.get("chat", "")
                if chat_str:
                    chat_id = int(json.loads(chat_str).get("id", 0))
            except Exception:
                pass

        if not chat_id:
            chat_id = x_chat_id

        # Per-chat check
        if chat_id:
            async with db.execute(
                f"SELECT COALESCE({module_key}, 1) FROM chat_settings WHERE chat_id = ?",
                (chat_id,),
            ) as c:
                row = await c.fetchone()
            if row and row[0] == 0:
                raise HTTPException(403, "🔧 Этот раздел временно недоступен в данном чате.")

        # Global check
        async with db.execute(
            "SELECT enabled FROM global_module_toggles WHERE module_key = ?",
            (module_key,),
        ) as c:
            grow = await c.fetchone()
        if grow and grow[0] == 0:
            raise HTTPException(403, "🔧 Этот раздел временно отключён глобально.")

    return _check


def require_tab_enabled(flag_key: str):
    """FastAPI dependency factory для GLOBAL-ONLY флагов из system_flags
    (админка «Глобальные модули», infrastructure/repositories/system_flags.py).

    Отдельно от require_module() выше: тот читает global_module_toggles/
    chat_settings (per-chat + отдельная global-таблица), этот — system_flags
    (только global, ключи tab_*). Раньше system_flags использовался ТОЛЬКО как
    UI-хинт (profile.py отдаёт его фронту, чтобы спрятать вкладку) — сам тумблер
    ничего на бэке не блокировал. Баг 2026-07-29: владелец выключил
    "Косметика/Образы" в админке, а /cosmetics/buy продолжал молча принимать
    покупки — вкладка пропадала из меню, но прямой запрос к API проходил.

    DEVELOPER_ID обходит тумблер — та же страховка, что в require_module()."""
    from infrastructure.repositories import system_flags as _flags_repo

    async def _check(db=Depends(get_db), user=Depends(require_tg_user_base)):
        if _DEV_ID and int(user["id"]) == _DEV_ID:
            return
        if not await _flags_repo.is_enabled(db, flag_key):
            raise HTTPException(403, "🔧 Этот раздел временно отключён.")

    return _check
