# Generated by Django 5.2.9 on 2026-02-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='photo',
            name='caption_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
    ]
