# Generated by Django 5.2.9 on 2026-01-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/events/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/previews/', verbose_name='Изображение превью'),
        ),
    ]
