# Generated by Django 5.2.9 on 2026-02-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_title_de_post_title_en_post_title_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Event Title'),
        ),
    ]
