# Generated by Django 5.2.8 on 2025-12-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='user',
            name='other_links',
            field=models.TextField(blank=True, verbose_name='Other links (one per line)'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Website'),
        ),
    ]
