# Generated by Django 5.2.9 on 2025-12-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_discord_url_user_github_url_user_other_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_comments_made',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Comments Made'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_likes_received',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Likes Received'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_posts',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Posts Published'),
        ),
    ]
