# Generated by Django 5.2.9 on 2025-12-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Activity Points'),
        ),
    ]
