# Generated by Django 5.2.9 on 2026-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_activity_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_physical_card',
            field=models.BooleanField(default=False, verbose_name='Has physical card'),
        ),
    ]
