# Generated by Django 5.2.9 on 2026-01-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_has_physical_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_physical_card',
        ),
    ]
