# Generated by Django 5.2.9 on 2026-01-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_user_username_idx_user_user_email_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_hidden',
            field=models.BooleanField(default=True, help_text='If checked, only admins can see your phone number', verbose_name='Hide Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
    ]
