# Generated by Django 5.2.9 on 2026-01-21 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0009_user_is_phone_hidden_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('business_type', models.CharField(choices=[('shop', 'Shop/Retail'), ('service', 'Service Provider'), ('gym', 'Gym/Fitness'), ('restaurant', 'Restaurant/Cafe'), ('other', 'Other')], default='other', max_length=100, verbose_name='Business Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'users_partner',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('purchase', 'Purchase'), ('consultation', 'Consultation'), ('training', 'Training Session'), ('event', 'Event Attendance'), ('other', 'Other')], default='other', max_length=100, verbose_name='Service Type')),
                ('service_description', models.TextField(blank=True, verbose_name='Service Description')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('pin_verified', models.BooleanField(default=False, verbose_name='PIN Verified')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Visit Time')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'db_table': 'users_visit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20, verbose_name='Membership Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pseudonym'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='32-char hex string for PIN generation', max_length=64, verbose_name='TOTP Secret'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['membership_status'], name='user_membership_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pseudonym'], name='user_pseudonym_idx'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddField(
            model_name='visit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='visit',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_visits', to='users.partner', verbose_name='Partner'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['company_name'], name='partner_company_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['business_type'], name='partner_business_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['-timestamp'], name='visit_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['partner', '-timestamp'], name='visit_partner_time_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['member', '-timestamp'], name='visit_member_time_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['pin_verified'], name='visit_verified_idx'),
        ),
    ]
