# Generated by Django 5.2.9 on 2026-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_partner_visit_user_membership_status_user_pseudonym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Base32-encoded secret for PIN generation', max_length=64, verbose_name='TOTP Secret'),
        ),
    ]
