# Generated by Django 5.2.9 on 2026-03-02 15:30

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_align_verbose_names_lazy'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
