# Generated by Django 5.2.9 on 2026-03-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False, help_text='Grant partner portal access without displaying on homepage. Partner can log member visits via the partner portal.', verbose_name='Partner Status'),
        ),
    ]
