# Generated by Django 5.2.9 on 2026-05-06 17:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_is_partner_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/', validators=[users.models._validate_avatar_size], verbose_name='Avatar'),
        ),
        migrations.AddIndex(
            model_name='visitaudit',
            index=models.Index(fields=['visit', '-changed_at'], name='audit_visit_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'EDITED', 'CANCELLED'])), name='valid_visit_status'),
        ),
    ]
