# Generated by Django 5.2.9 on 2026-05-12 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_accountchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountchangerequest',
            name='address',
            field=models.TextField(blank=True, help_text='City, street, or region where you operate.', verbose_name='Address / Location'),
        ),
        migrations.AddField(
            model_name='accountchangerequest',
            name='business_category',
            field=models.CharField(blank=True, choices=[('gym', 'Gym / Fitness Center'), ('martial_arts', 'Martial Arts School'), ('yoga_pilates', 'Yoga / Pilates Studio'), ('swimming', 'Swimming Pool / Aquatics'), ('sports_club', 'Sports Club / Team'), ('personal_trainer', 'Personal Trainer / Coach'), ('crossfit', 'CrossFit / Functional Training'), ('cycling', 'Cycling / Indoor Cycling'), ('dance', 'Dance School'), ('climbing', 'Climbing / Boulder'), ('physiotherapy', 'Physiotherapy / Rehabilitation'), ('massage_spa', 'Massage / SPA / Wellness'), ('nutrition', 'Nutrition / Dietology'), ('medical', 'Medical / Healthcare'), ('psychology', 'Psychology / Mental Health'), ('chiropractic', 'Chiropractic / Manual Therapy'), ('sports_shop', 'Sports Equipment Shop'), ('clothing', 'Sports Clothing / Gear'), ('supplement', 'Sports Supplements / Nutrition Products'), ('bike_shop', 'Bike Shop / Service'), ('lawyer', 'Legal Services / Lawyer'), ('accountant', 'Accounting / Finance'), ('consulting', 'Business Consulting'), ('marketing', 'Marketing / PR / Design'), ('hr', 'HR / Recruitment'), ('it', 'IT / Technology / Software'), ('coach_trainer', 'Professional Coaching'), ('school', 'School / Educational Center'), ('event_org', 'Event Organization'), ('seminar', 'Seminar / Workshop Host'), ('travel', 'Travel / Tourism / Adventure'), ('outdoor', 'Outdoor Activities / Hiking'), ('water_sports', 'Water Sports / Diving / Surfing'), ('winter_sports', 'Winter Sports / Ski'), ('restaurant', 'Restaurant / Cafe / Bar'), ('healthy_food', 'Healthy Food / Catering'), ('hotel', 'Hotel / Accommodation'), ('media', 'Media / Content Creation / Photography'), ('esports', 'eSports / Gaming'), ('other', 'Other (describe in the form)')], help_text='Most accurately describes your activity area.', max_length=50, verbose_name='Business Category'),
        ),
        migrations.AddField(
            model_name='accountchangerequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='accountchangerequest',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Full name of the contact person.', max_length=200, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='accountchangerequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone / WhatsApp'),
        ),
        migrations.AddField(
            model_name='accountchangerequest',
            name='contact_telegram',
            field=models.CharField(blank=True, help_text='@username or phone number', max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='accountchangerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g. "Personal training", "Consultation", "Trial class"', max_length=255, verbose_name='Meeting Title')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Address / Location')),
                ('notes', models.TextField(blank=True, help_text='Additional details for the member.', verbose_name='Notes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20, verbose_name='Status')),
                ('notify_member', models.BooleanField(default=True, help_text='Send TG and site notification to the member when created.', verbose_name='Notify Member')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='users.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'users_meeting',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['partner', 'date'], name='meeting_partner_date_idx'), models.Index(fields=['member', 'date'], name='meeting_member_date_idx'), models.Index(fields=['date', 'status'], name='meeting_date_status_idx')],
            },
        ),
    ]
