# Generated by Django 5.2.9 on 2026-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_acr_contact_fields_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Membership Status'),
        ),
    ]
