# Generated by Django 5.2.9 on 2026-05-12 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_meeting_optional_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Mark if this is part of an ongoing series (insurance, coaching, therapy...)', verbose_name='Recurring Meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='series_label',
            field=models.CharField(blank=True, help_text='E.g. "Monthly review", "Rehab program Q1", "Insurance case #123"', max_length=100, verbose_name='Series / Project Label'),
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Note')),
                ('is_pinned', models.BooleanField(default=False, help_text='Show this note at the top', verbose_name='Pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_notes', to=settings.AUTH_USER_MODEL, verbose_name='Member / Client')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='users.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Client Note',
                'verbose_name_plural': 'Client Notes',
                'db_table': 'users_clientnote',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['partner', 'member'], name='clientnote_partner_member_idx')],
            },
        ),
    ]
