# Generated by Django 5.2.9 on 2026-05-12 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_meeting_recurring_clientnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
                'db_table': 'users_sitesettings',
            },
        ),
        migrations.CreateModel(
            name='AdminNotificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_events', models.JSONField(default=list, help_text='Список кодов событий. Пример: ["new_account", "insurance_request"]', verbose_name='События в Telegram')),
                ('site_events', models.JSONField(default=list, help_text='Список кодов событий для уведомлений внутри сайта', verbose_name='События на сайте')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы приостановить все уведомления для этого администратора', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Профиль уведомлений администратора',
                'verbose_name_plural': 'Профили уведомлений администраторов',
                'db_table': 'users_adminnotificationprofile',
            },
        ),
        migrations.CreateModel(
            name='InsuranceAgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('new_agent', 'Нужен страховой агент'), ('change_agent', 'Смена страхового агента'), ('consultation', 'Консультация по страхованию')], default='new_agent', max_length=20, verbose_name='Тип заявки')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram_username', models.CharField(blank=True, help_text='@username', max_length=100, verbose_name='Telegram')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город / Регион')),
                ('insurance_types', models.CharField(blank=True, help_text='Жизнь, здоровье, спорт, автомобиль...', max_length=500, verbose_name='Виды страхования')),
                ('message', models.TextField(blank=True, help_text='Особые пожелания, вопросы, детали ситуации', verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('reviewing', 'На рассмотрении'), ('assigned', 'Агент назначен'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('assigned_agent', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_insurance_requests', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный агент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на страхового агента',
                'verbose_name_plural': 'Заявки на страховых агентов',
                'db_table': 'users_insuranceagentrequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ins_status_date_idx'), models.Index(fields=['user'], name='ins_user_idx')],
            },
        ),
    ]
