# Generated by Django 5.2.9 on 2026-05-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_insurance_agent_request_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarded',
            field=models.BooleanField(default=False, help_text='True после того как пользователь прошёл welcome-modal', verbose_name='Onboarded'),
        ),
    ]
