# Generated by Django 5.2.9 on 2026-05-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_add_user_onboarded_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address_full',
            field=models.CharField(blank=True, default='', help_text='Street, city, country — shown on map', max_length=512, verbose_name='Full Address'),
        ),
        migrations.AddField(
            model_name='partner',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='partner',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
