# Generated by Django 5.2.9 on 2026-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_drop_orphaned_messaging_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchangerequest',
            name='business_category',
            field=models.CharField(blank=True, choices=[('gym', 'Gym / Fitness Center'), ('martial_arts', 'Martial Arts School'), ('yoga_pilates', 'Yoga / Pilates Studio'), ('swimming', 'Swimming Pool / Aquatics'), ('sports_club', 'Sports Club / Team'), ('personal_trainer', 'Personal Trainer / Coach'), ('crossfit', 'CrossFit / Functional Training'), ('cycling', 'Cycling / Indoor Cycling'), ('dance', 'Dance School'), ('climbing', 'Climbing / Boulder'), ('physiotherapy', 'Physiotherapy / Rehabilitation'), ('massage_spa', 'Massage / SPA / Wellness'), ('nutrition', 'Nutrition / Dietology'), ('medical', 'Medical / Healthcare'), ('psychology', 'Psychology / Mental Health'), ('chiropractic', 'Chiropractic / Manual Therapy'), ('sports_shop', 'Sports Equipment Shop'), ('clothing', 'Sports Clothing / Gear'), ('supplement', 'Sports Supplements / Nutrition Products'), ('bike_shop', 'Bike Shop / Service'), ('insurance_agent', 'Insurance Agent / Broker'), ('bank', 'Bank / Banking Services'), ('financial_advisor', 'Financial Advisor'), ('lawyer', 'Legal Services / Lawyer'), ('accountant', 'Accounting / Finance'), ('consulting', 'Business Consulting'), ('marketing', 'Marketing / PR / Design'), ('hr', 'HR / Recruitment'), ('it', 'IT / Technology / Software'), ('coach_trainer', 'Professional Coaching'), ('school', 'School / Educational Center'), ('event_org', 'Event Organization'), ('seminar', 'Seminar / Workshop Host'), ('travel', 'Travel / Tourism / Adventure'), ('outdoor', 'Outdoor Activities / Hiking'), ('water_sports', 'Water Sports / Diving / Surfing'), ('winter_sports', 'Winter Sports / Ski'), ('restaurant', 'Restaurant / Cafe / Bar'), ('healthy_food', 'Healthy Food / Catering'), ('hotel', 'Hotel / Accommodation'), ('media', 'Media / Content Creation / Photography'), ('esports', 'eSports / Gaming'), ('other', 'Other (describe in the form)')], help_text='Most accurately describes your activity area.', max_length=50, verbose_name='Business Category'),
        ),
    ]
