# Generated by Django 5.2.9 on 2026-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_accountchangerequest_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountchangerequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='accountchangerequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='accountchangerequest',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Deprecated: now stored as first_name + last_name. Kept for backward compatibility.', max_length=200, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='accountchangerequest',
            name='desired_type',
            field=models.CharField(choices=[('partner', 'External Partner'), ('association_staff', 'Association Staff (IESA)'), ('president', 'President of Association')], max_length=50, verbose_name='Desired Account Type'),
        ),
    ]
