# Generated by Django 5.2.9 on 2026-05-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_create_notification_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountchangerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Shown to user if request is rejected.', verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='accountchangerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AddField(
            model_name='accountchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_president',
            field=models.BooleanField(default=False, help_text='Marks user as president of the association. Displayed with a crown badge.', verbose_name='President of Association'),
        ),
        migrations.AlterField(
            model_name='accountchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by user')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
