"""Константы для приложения blog"""

# Pagination
POSTS_PER_PAGE = 10
EVENTS_PER_PAGE = 12
SEARCH_RESULTS_LIMIT = 12

# Search
MIN_SEARCH_LENGTH = 2
SEARCH_USERS_LIMIT = 8
SEARCH_POSTS_LIMIT = 6
SEARCH_EVENTS_LIMIT = 6
SEARCH_PARTNERS_LIMIT = 6

# Cache
QR_CACHE_TIMEOUT = 3600  # 1 hour
SEARCH_CACHE_TIMEOUT = 300  # 5 minutes

# Engagement weights
LIKE_WEIGHT = 2
COMMENT_WEIGHT = 3
