# Generated by Django 5.2.9 on 2026-01-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_approved', 'Post Approved'), ('post_rejected', 'Post Rejected'), ('new_comment', 'New Comment'), ('comment_reply', 'Comment Reply'), ('new_like', 'New Like'), ('new_follower', 'New Follower'), ('event_reminder', 'Event Reminder'), ('new_message', 'New Message'), ('system', 'System Notification')], max_length=20, verbose_name='Type'),
        ),
    ]
